1,r2/commands.py,62,F0401,Unable to import 'setproctitle',,1,
2,r2/commands.py,115,W0122,Use of the exec statement,,1,
3,r2/commands.py,42,R0904,Too many public methods (21/20),,1,"Extends another class, but add only 1 method"
5,r2/lib/promote.py,190,E1101,Module 'hashlib' has no 'sha1' member,,1,
6,r2/lib/promote.py,202,E1101,Module 'hashlib' has no 'sha1' member,,1,
7,r2/lib/promote.py,264,W0621,Redefining name 'c' from outer scope (line 35),,0,"c is an import module, but is also used as a variable name later (line 264)"
8,r2/lib/promote.py,274,R0913,Too many arguments (7/5),,1,Bad smell but not a problem
9,r2/lib/promote.py,293,R0913,Too many arguments (8/5),,1,Bad smell but not a problem
10,r2/lib/promote.py,359,E1123,Passing unexpected keyword argument '_update' in function call,,1,"function called is ""memoized"""
11,r2/lib/promote.py,379,E1101,Module 'r2.lib.authorize' has no 'void_transaction' member,,1,function in r2/lib/authorize/interaction.py:180
12,r2/lib/promote.py,407,E1101,Module 'r2.lib.authorize' has no 'auth_transaction' member,,1,function in r2/lib/authorize/interaction.py:140
13,r2/lib/promote.py,485,E1123,Passing unexpected keyword argument '_update' in function call,,1,"function called is ""memoized"""
14,r2/lib/promote.py,499,E1123,Passing unexpected keyword argument '_update' in function call,,1,"function called is ""memoized"""
15,r2/lib/promote.py,522,E1101,Module 'r2.lib.authorize' has no 'is_charged_transaction' member,,1,function in r2/lib/authorize/interaction.py:191
16,r2/lib/promote.py,590,E1101,Module 'r2.lib.authorize' has no 'charge_transaction' member,,1,function in r2/lib/authorize/interaction.py:205
17,r2/lib/promote.py,662,E1123,Passing unexpected keyword argument '_update' in function call,,1,same as above
18,r2/lib/promote.py,669,R0914,Too many local variables (16/15),,0,probably better to split in some functions
19,r2/lib/promote.py,687,W0612,Unused variable 'end',,0,
20,r2/lib/promote.py,738,E1101,Module 'r2.lib.authorize' has no 'refund_transaction' member,,1,r2/lib/authorize/interacion.py:230
21,r2/lib/promote.py,740,E1101,Module 'r2.lib.authorize' has no 'AuthorizeNetException' member,,1,r2/lib/authorize/api.py:59
22,r2/lib/promote.py,738,W0612,Unused variable 'success',,0,
24,r2/lib/tracking.py,167,E1101,Module 'hashlib' has no 'sha1' member,,1,
26,r2/lib/translation.py,72,W0612,Unused variable 'dialect',,0,
27,r2/lib/translation.py,118,W0612,Unused variable 'dialect',,0,
28,r2/lib/translation.py,175,W0612,Unused variable 'func',,0,
29,r2/lib/translation.py,175,W0612,Unused variable 'line',,0,
30,r2/lib/translation.py,175,W0612,Unused variable 'comments',,0,
31,r2/lib/nymph.py,94,E1101,Module 'hashlib' has no 'md5' member,,1,
32,r2/lib/nymph.py,127,W0622,Redefining built-in 'bin',,1,redefined as a temporary variable in a for loop
33,r2/lib/nymph.py,136,W0631,Using possibly undefined loop variable 'bin',,0,
34,r2/lib/jsontemplates.py,878,W0311,Bad indentation. Found 13 spaces,expected 12,0,
35,r2/lib/jsontemplates.py,886,W0311,Bad indentation. Found 5 spaces,expected 4,0,
36,r2/lib/jsontemplates.py,887,W0311,Bad indentation. Found 9 spaces,expected 8,0,
37,r2/lib/jsontemplates.py,889,W0311,Bad indentation. Found 5 spaces,expected 4,0,
38,r2/lib/jsontemplates.py,890,W0311,Bad indentation. Found 9 spaces,expected 8,0,
39,r2/lib/jsontemplates.py,891,W0311,Bad indentation. Found 9 spaces,expected 8,0,
40,r2/lib/jsontemplates.py,913,W0311,Bad indentation. Found 14 spaces,expected 16,0,
41,r2/lib/jsontemplates.py,917,W0311,Bad indentation. Found 14 spaces,expected 16,0,
43,r2/lib/jsontemplates.py,25,W0403,Relative import 'utils',should be 'r2.lib.utils',0,
44,r2/lib/jsontemplates.py,26,W0403,Relative import 'wrapped',should be 'r2.lib.wrapped',0,
45,r2/lib/jsontemplates.py,48,W0231,__init__ method from base class 'StringTemplate' is not called,,0,
46,r2/lib/jsontemplates.py,66,W0102,Dangerous default value {} as argument,,0,Bad smell !
47,r2/lib/jsontemplates.py,70,W0231,__init__ method from base class 'Template' is not called,,0,
48,r2/lib/jsontemplates.py,70,C0321,More than one statement on a single line,,0,
49,r2/lib/jsontemplates.py,72,W0613,Unused argument 'a',,0,
50,r2/lib/jsontemplates.py,72,W0613,Unused argument 'thing',,0,
51,r2/lib/jsontemplates.py,72,W0613,Unused argument 'kw',,0,
52,r2/lib/jsontemplates.py,127,R0911,Too many return statements (20/6),,0,
53,r2/lib/jsontemplates.py,198,W0613,Unused argument 'action',,0,
54,r2/lib/jsontemplates.py,262,R0911,Too many return statements (9/6),,0,
55,r2/lib/jsontemplates.py,363,R0911,Too many return statements (8/6),,0,
56,r2/lib/jsontemplates.py,404,W0231,__init__ method from base class 'ThingJsonTemplate' is not called,,0,
57,r2/lib/jsontemplates.py,462,R0911,Too many return statements (11/6),,0,
58,r2/lib/jsontemplates.py,548,R0911,Too many return statements (10/6),,0,
59,r2/lib/jsontemplates.py,549,W0612,Unused variable 'Subreddit',,0,
60,r2/lib/jsontemplates.py,639,R0911,Too many return statements (13/6),,0,
61,r2/lib/jsontemplates.py,786,W0612,Unused variable 'splitter',,0,
62,r2/lib/jsontemplates.py,863,W0613,Unused argument 'thing',,0,
63,r2/lib/jsontemplates.py,871,W0613,Unused argument 'thing',,0,
64,r2/lib/jsontemplates.py,886,W0613,Unused argument 'thing',,0,
65,r2/lib/jsontemplates.py,1139,W0612,Unused variable 'splitter',,0,
66,r2/lib/mr_top.py,110,W0622,Redefining built-in 'id',,0,
70,r2/lib/app_globals.py,116,W0622,Redefining built-in 'type',,0,
71,r2/lib/app_globals.py,138,R0902,Too many instance attributes (56/7),,0,
72,r2/lib/app_globals.py,324,W0613,Unused argument 'extra',,0,
73,r2/lib/app_globals.py,324,W0613,Unused argument 'app_conf',,0,
74,r2/lib/app_globals.py,398,R0914,Too many local variables (36/15),,0,
75,r2/lib/app_globals.py,398,R0912,Too many branches (29/25),,0,
76,r2/lib/app_globals.py,777,R0914,Too many local variables (17/15),,0,
77,r2/lib/app_globals.py,467,E0203,Access to member 'media_domain' before its definition line 468,,1,media_domain is defined in the configuration file who will inject the member 'media_domain' in this class
78,r2/lib/app_globals.py,423,W0201,Attribute 'origin' defined outside __init__,,0,Is that really risky ?
79,r2/lib/app_globals.py,636,W0201,Attribute 'dbm' defined outside __init__,,0,
80,r2/lib/app_globals.py,679,W0201,Attribute 'ratelimitcache' defined outside __init__,,0,
81,r2/lib/app_globals.py,402,W0201,Attribute 'media_provider' defined outside __init__,,0,
82,r2/lib/app_globals.py,570,W0201,Attribute 'make_lock' defined outside __init__,,0,
83,r2/lib/app_globals.py,522,W0201,Attribute 'live_config' defined outside __init__,,0,
84,r2/lib/app_globals.py,420,W0201,Attribute 'read_only_mode' defined outside __init__,,0,
85,r2/lib/app_globals.py,465,W0201,Attribute 'locations' defined outside __init__,,0,
86,r2/lib/app_globals.py,779,W0201,Attribute 'db_params' defined outside __init__,,0,
87,r2/lib/app_globals.py,725,W0201,Attribute 'reset_caches' defined outside __init__,,0,
88,r2/lib/app_globals.py,462,W0201,Attribute 'log' defined outside __init__,,0,
89,r2/lib/app_globals.py,494,W0201,Attribute 'RL_OAUTH_RESET_SECONDS' defined outside __init__,,0,
90,r2/lib/app_globals.py,654,W0201,Attribute 'cache' defined outside __init__,,0,
91,r2/lib/app_globals.py,568,W0201,Attribute 'lock_cache' defined outside __init__,,,
92,r2/lib/app_globals.py,495,W0201,Attribute 'RL_OAUTH_MAX_REQS' defined outside __init__,,,
93,r2/lib/app_globals.py,524,W0201,Attribute 'throttles' defined outside __init__,,,
94,r2/lib/app_globals.py,518,W0201,Attribute 'zookeeper' defined outside __init__,,,
95,r2/lib/app_globals.py,480,W0201,Attribute 'reddit_host' defined outside __init__,,,
96,r2/lib/app_globals.py,675,W0201,Attribute 'srmembercache' defined outside __init__,,,
97,r2/lib/app_globals.py,531,W0201,Attribute 'sponsors' defined outside __init__,,,
98,r2/lib/app_globals.py,734,W0201,Attribute 'short_version' defined outside __init__,,,
99,r2/lib/app_globals.py,612,W0201,Attribute 'cassandra_pools' defined outside __init__,,,
100,r2/lib/app_globals.py,540,W0201,Attribute 'memcache' defined outside __init__,,,
101,r2/lib/app_globals.py,699,W0201,Attribute 'permacache' defined outside __init__,,,
102,r2/lib/app_globals.py,696,W0201,Attribute 'thing_cache' defined outside __init__,,,
103,r2/lib/app_globals.py,683,W0201,Attribute 'rendercache' defined outside __init__,,,
104,r2/lib/app_globals.py,824,W0201,Attribute 'predefined_type_ids' defined outside __init__,,,
105,r2/lib/app_globals.py,468,W0201,Attribute 'media_domain' defined outside __init__,,,
106,r2/lib/app_globals.py,664,W0201,Attribute 'memoizecache' defined outside __init__,,,
107,r2/lib/app_globals.py,709,W0201,Attribute 'hardcache' defined outside __init__,,,
108,r2/lib/app_globals.py,523,W0201,Attribute 'secrets' defined outside __init__,,,
109,r2/lib/app_globals.py,689,W0201,Attribute 'pagecache' defined outside __init__,,,
110,r2/lib/app_globals.py,399,W0201,Attribute 'queues' defined outside __init__,,,
111,r2/lib/app_globals.py,731,W0201,Attribute 'versions' defined outside __init__,,,
112,r2/lib/app_globals.py,490,W0201,Attribute 'RL_RESET_SECONDS' defined outside __init__,,,
113,r2/lib/app_globals.py,529,W0201,Attribute 'admins' defined outside __init__,,,
114,r2/lib/app_globals.py,425,W0201,Attribute 'trusted_domains' defined outside __init__,,,
115,r2/lib/app_globals.py,778,W0201,Attribute 'databases' defined outside __init__,,0,
116,r2/lib/app_globals.py,481,W0201,Attribute 'reddit_pid' defined outside __init__,,0,
117,r2/lib/app_globals.py,723,W0201,Attribute 'cache_chains' defined outside __init__,,0,
118,r2/lib/app_globals.py,491,W0201,Attribute 'RL_MAX_REQS' defined outside __init__,,0,
119,r2/lib/app_globals.py,533,W0201,Attribute 'employees' defined outside __init__,,0,
120,r2/lib/app_globals.py,437,W0201,Attribute 'static_names' defined outside __init__,,0,
121,r2/lib/sup.py,56,E1101,Module 'hashlib' has no 'md5' member,,1,
122,r2/lib/sup.py,85,W0621,Redefining name 'time' from outer scope (line 25),,0,
124,r2/lib/memoize.py,35,W0621,Redefining name 'NoneResult' from outer scope (line 26),,0,
127,r2/lib/emailer.py,124,C0324,Comma not followed by a space,,0,
130,r2/lib/csrf.py,44,W0612,Unused variable 'sep',,0,
131,r2/lib/inventory_optimization.py,112,R0914,Too many local variables (20/15),,0,
132,r2/lib/inventory_optimization.py,175,W0612,Unused variable 'changed_1',,0,
133,r2/lib/inventory_optimization.py,187,R0914,Too many local variables (21/15),,0,
134,r2/lib/inventory_optimization.py,380,W0105,String statement has no effect,,0,Bad comment style..
135,r2/lib/gzipper.py,122,W0622,Redefining built-in 'type',,0,
136,r2/lib/gzipper.py,122,W0612,Unused variable 'params',,0,
137,r2/lib/gzipper.py,64,W0201,Attribute 'status' defined outside __init__,,0,
138,r2/lib/gzipper.py,65,W0201,Attribute 'headers' defined outside __init__,,0,
139,r2/lib/gzipper.py,66,W0201,Attribute 'exc_info' defined outside __init__,,0,
140,r2/lib/gzipper.py,188,W0613,Unused argument 'global_conf',,0,
142,r2/lib/cloudsearch.py,82,C0321,More than one statement on a single line,,0,
143,r2/lib/cloudsearch.py,83,C0321,More than one statement on a single line,,0,
144,r2/lib/cloudsearch.py,120,C0203,"Metaclass method should have ""mcs"" as first argument",,0,convention
145,r2/lib/cloudsearch.py,134,W0621,Redefining name 'field' from outer scope (line 91),,0,
146,r2/lib/cloudsearch.py,134,E1101,Instance of 'FieldsBase' has no '_fields' member,,0,"FieldsMeta is a superclass of FieldsBase, and FM has cls._fields"
147,r2/lib/cloudsearch.py,144,E1101,Class 'FieldsBase' has no '_fields' member,,0,
148,r2/lib/cloudsearch.py,149,E1101,Class 'FieldsBase' has no '_fields' member,,0,
149,r2/lib/cloudsearch.py,154,E1101,Class 'FieldsBase' has no '_fields' member,,0,
150,r2/lib/cloudsearch.py,167,W0231,__init__ method from base class 'FieldsBase' is not called,,0,
151,r2/lib/cloudsearch.py,166,R0904,Too many public methods (28/20),,0,
152,r2/lib/cloudsearch.py,277,W0231,__init__ method from base class 'FieldsBase' is not called,,0,
153,r2/lib/cloudsearch.py,368,W0621,Redefining name 'field' from outer scope (line 91),,0,
154,r2/lib/cloudsearch.py,433,W0201,Attribute 'things' defined outside __init__,,0,
155,r2/lib/cloudsearch.py,585,W0613,Unused argument 'chan',,0,
156,r2/lib/cloudsearch.py,614,R0913,Too many arguments (6/5),,0,
157,r2/lib/cloudsearch.py,634,R0913,Too many arguments (7/5),,0,
158,r2/lib/cloudsearch.py,739,R0913,Too many arguments (9/5),,0,
159,r2/lib/cloudsearch.py,739,R0914,Too many local variables (17/15),,0,
160,r2/lib/cloudsearch.py,797,R0913,Too many arguments (7/5),,0,
161,r2/lib/cloudsearch.py,822,R0902,Too many instance attributes (11/7),,0,
162,r2/lib/cloudsearch.py,832,R0913,Too many arguments (8/5),,0,
163,r2/lib/cloudsearch.py,897,R0913,Too many arguments (8/5),,0,
164,r2/lib/cloudsearch.py,897,R0914,Too many local variables (17/15),,1,
165,r2/lib/cloudsearch.py,898,W0613,Unused argument '_update',,0,
166,r2/lib/configparse.py,30,W0613,Unused argument 'key',,0,
167,r2/lib/configparse.py,34,W0613,Unused argument 'key',,0,
168,r2/lib/configparse.py,38,W0613,Unused argument 'key',,0,
169,r2/lib/configparse.py,51,W0613,Unused argument 'key',,0,
170,r2/lib/configparse.py,56,W0613,Unused argument 'key',,0,
171,r2/lib/configparse.py,62,W0613,Unused argument 'key',,0,
172,r2/lib/configparse.py,82,W0613,Unused argument 'key',,0,
173,r2/lib/configparse.py,92,W0613,Unused argument 'key',,0,
175,r2/lib/menus.py,188,W0622,Redefining built-in 'type',,0,
176,r2/lib/menus.py,210,R0913,Too many arguments (9/5),,0,
177,r2/lib/menus.py,210,W0622,Redefining built-in 'type',,0,
178,r2/lib/menus.py,263,R0902,Too many instance attributes (11/7),,0,
179,r2/lib/menus.py,271,R0913,Too many arguments (9/5),,0,
180,r2/lib/menus.py,293,W0201,Attribute 'bare_path' defined outside __init__,,0,
181,r2/lib/menus.py,294,W0201,Attribute 'base_path' defined outside __init__,,0,
182,r2/lib/menus.py,301,W0201,Attribute 'path' defined outside __init__,,0,
183,r2/lib/menus.py,335,R0913,Too many arguments (8/5),,0,
184,r2/lib/menus.py,294,W0201,Attribute 'base_path' defined outside __init__,,0,
185,r2/lib/menus.py,301,W0201,Attribute 'path' defined outside __init__,,0,
186,r2/lib/menus.py,362,R0913,Too many arguments (8/5),,0,
187,r2/lib/menus.py,371,W0201,Attribute 'action_params' defined outside __init__,,0,
188,r2/lib/menus.py,294,W0201,Attribute 'base_path' defined outside __init__,,0,
189,r2/lib/menus.py,301,W0201,Attribute 'path' defined outside __init__,,0,
190,r2/lib/menus.py,293,W0201,Attribute 'bare_path' defined outside __init__,,0,
191,r2/lib/menus.py,293,W0201,Attribute 'bare_path' defined outside __init__,,0,
192,r2/lib/menus.py,450,R0913,Too many arguments (9/5),,0,
193,r2/lib/menus.py,450,W0102,Dangerous default value {} as argument,,0,
194,r2/lib/menus.py,301,W0201,Attribute 'path' defined outside __init__,,0,
195,r2/lib/menus.py,512,R0913,Too many arguments (7/5),,0,
196,r2/lib/menus.py,575,E1101,Class 'SearchSortMenu' has no 'default' member,,1,Superclass (NavMenu) of superclass (SortMenu) has a 'default' member
197,r2/lib/menus.py,604,C0202,Class method should have 'cls' as first argument,,0,
198,r2/lib/static.py,60,E1101,Module 'hashlib' has no 'sha1' member,,1,
200,r2/lib/cache.py,44,C0321,More than one statement on a single line,,0,
201,r2/lib/cache.py,54,E1101,Instance of 'CacheUtils' has no 'incr' member,,0,
202,r2/lib/cache.py,59,C0324,Comma not followed by a space,,0,
205,r2/lib/cache.py,60,E1101,Instance of 'CacheUtils' has no 'add' member,,0,
206,r2/lib/cache.py,63,E1101,Instance of 'CacheUtils' has no 'simple_get_multi' member,,0,
207,r2/lib/cache.py,66,R0913,Too many arguments (7/5),,0,
208,r2/lib/cache.py,66,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
209,r2/lib/cache.py,68,W0613,Unused argument 'debug',,0,
210,r2/lib/cache.py,75,W0612,Unused variable 'x',,0,
211,r2/lib/cache.py,117,C0324,Comma not followed by a space,,0,
214,r2/lib/cache.py,126,C0324,Comma not followed by a space,,0,
217,r2/lib/cache.py,142,W0613,Unused argument 'time',,0,
218,r2/lib/cache.py,151,E1101,Module 'pylibmc' has no 'DataExists' member,,0,
219,r2/lib/cache.py,154,W0613,Unused argument 'time',,0,
220,r2/lib/cache.py,170,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
221,r2/lib/cache.py,206,C0324,Comma not followed by a space,,0,
224,r2/lib/cache.py,213,C0321,More than one statement on a single line,,0,
225,r2/lib/cache.py,216,W0613,Unused argument 'time',,0,
226,r2/lib/cache.py,232,E0101,Explicit return in __init__,,0,Is __init__ supposed to return something ?
227,r2/lib/cache.py,232,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
228,r2/lib/cache.py,243,C0321,More than one statement on a single line,,0,
229,r2/lib/cache.py,253,W0613,Unused argument 'time',,0,
230,r2/lib/cache.py,259,C0324,Comma not followed by a space,,0,
233,r2/lib/cache.py,262,W0613,Unused argument 'time',,0,
234,r2/lib/cache.py,277,W0613,Unused argument 'time',,0,
235,r2/lib/cache.py,285,W0613,Unused argument 'time',,0,
236,r2/lib/cache.py,289,W0613,Unused argument 'time',,0,
237,r2/lib/cache.py,293,W0613,Unused argument 'time',,0,
238,r2/lib/cache.py,231,R0904,Too many public methods (32/20),,0,
239,r2/lib/cache.py,326,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
240,r2/lib/cache.py,338,E0213,"Method should have ""self"" as first argument",,0,
241,r2/lib/cache.py,350,E0213,"Method should have ""self"" as first argument",,0,
242,r2/lib/cache.py,374,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
243,r2/lib/cache.py,374,W0231,__init__ method from base class '_local' is not called,,1,The class does not have a '_local' superclass
244,r2/lib/cache.py,374,W0231,__init__ method from base class 'local' is not called,,0,
245,r2/lib/cache.py,379,E0213,"Method should have ""self"" as first argument",,0,
246,r2/lib/cache.py,412,C0324,Comma not followed by a space,,0,
249,r2/lib/cache.py,408,W0613,Unused argument 'stale',,0,
250,r2/lib/cache.py,448,W0613,Unused argument 'stale',,0,
251,r2/lib/cache.py,554,W0231,__init__ method from base class 'CacheChain' is not called,,0,
252,r2/lib/cache.py,713,W0105,String statement has no effect,,0,Badly used as a comment
253,r2/lib/cache.py,714,W0231,__init__ method from base class 'CacheUtils' is not called,,0,
254,r2/lib/cache.py,803,C0324,Comma not followed by a space,,0,
257,r2/lib/cache.py,804,C0324,Comma not followed by a space,,0,
260,r2/lib/cache.py,837,C0324,Comma not followed by a space,,0,
263,r2/lib/cache.py,854,C0324,Comma not followed by a space,,0,
266,r2/lib/cache.py,853,W0612,Unused variable 'y',,0,
267,r2/lib/cache.py,866,W0231,__init__ method from base class 'LocalCache' is not called,,0,
268,r2/lib/cache.py,875,C0324,Comma not followed by a space,,0,
271,r2/lib/cache.py,865,R0904,Too many public methods (33/20),,0,Because superclass (LocalCache) has to many public methods
275,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
276,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
277,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
278,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
279,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
280,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
281,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
282,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
283,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
284,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
285,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
286,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
287,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
288,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
289,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
290,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
291,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
292,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
293,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
294,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
295,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
296,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
297,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
298,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
299,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
300,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
301,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
302,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
303,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
304,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
305,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
306,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
307,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
308,r2/lib/wrapped.so,1,R0902,Too many instance attributes (33/7),,,
309,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
310,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
311,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
312,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
313,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
314,r2/models/builder.py,136,W0201,Attribute 'attribs' defined outside __init__,,0,
315,r2/models/builder.py,245,W0201,Attribute 'moderator_banned' defined outside __init__,,0,
316,r2/models/builder.py,257,W0201,Attribute '_spam' defined outside __init__,,0,
317,r2/models/builder.py,1103,W0201,Attribute 'is_parent' defined outside __init__,,0,
318,r2/models/builder.py,246,W0201,Attribute 'autobanned' defined outside __init__,,0,
319,r2/models/builder.py,189,W0201,Attribute 'subreddit' defined outside __init__,,0,
320,r2/models/builder.py,191,W0201,Attribute 'likes' defined outside __init__,,0,
321,r2/models/builder.py,241,W0201,Attribute 'unbanner' defined outside __init__,,0,
322,r2/models/builder.py,196,W0201,Attribute 'score' defined outside __init__,,0,
323,r2/models/builder.py,147,W0201,Attribute 'author' defined outside __init__,,0,
324,r2/models/builder.py,269,W0201,Attribute 'report_count' defined outside __init__,,0,
325,r2/lib/pages/things.py,216,W0201,Attribute 'render_class' defined outside __init__,,0,
326,r2/models/builder.py,238,W0201,Attribute 'can_ban' defined outside __init__,,0,
327,r2/lib/pages/things.py,219,W0201,Attribute 'should_incr_counts' defined outside __init__,,0,
328,r2/models/builder.py,256,W0201,Attribute 'show_spam' defined outside __init__,,0,
329,r2/models/builder.py,150,W0201,Attribute 'friend' defined outside __init__,,0,
330,r2/models/builder.py,959,W0201,Attribute 'count' defined outside __init__,,0,
331,r2/models/builder.py,209,W0201,Attribute 'deleted' defined outside __init__,,0,
332,r2/models/builder.py,223,W0201,Attribute 'ip_span' defined outside __init__,,0,
333,r2/models/builder.py,1109,W0201,Attribute 'collapsed' defined outside __init__,,0,
334,r2/models/builder.py,248,W0201,Attribute 'banned_at' defined outside __init__,,0,
335,r2/models/builder.py,290,W0201,Attribute 'approval_checkmark' defined outside __init__,,0,
336,r2/models/builder.py,710,W0201,Attribute 'show_extended' defined outside __init__,,0,
337,r2/models/builder.py,247,W0201,Attribute 'banner' defined outside __init__,,0,
338,r2/models/builder.py,1107,W0201,Attribute 'focal' defined outside __init__,,0,
339,r2/models/builder.py,711,W0201,Attribute 'show_compare' defined outside __init__,,0,
340,r2/models/builder.py,264,W0201,Attribute 'use_big_modbuttons' defined outside __init__,,0,
341,r2/models/builder.py,263,W0201,Attribute 'show_reports' defined outside __init__,,0,
342,r2/lib/pages/things.py,218,W0201,Attribute 'score_fmt' defined outside __init__,,0,
343,r2/models/builder.py,207,W0201,Attribute 'voting_score' defined outside __init__,,0,
344,r2/models/builder.py,621,W0201,Attribute 'fullname' defined outside __init__,,0,
345,r2/models/builder.py,211,W0201,Attribute 'link_notes' defined outside __init__,,0,
346,r2/models/builder.py,144,W0201,Attribute 'distinguished' defined outside __init__,,0,
347,r2/lib/wrapped.so,1,E0611,No name '__class__' in module '__builtin__',,,
348,r2/lib/wrapped.so,1,E0611,No name '__new__' in module '__builtin__',,,
349,r2/lib/wrapped.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
350,r2/lib/wrapped.so,1,W0232,Class has no __init__ method,,,
352,r2/lib/template_helpers.py,27,W0403,Relative import 'filters',should be 'r2.lib.filters',0,
353,r2/lib/template_helpers.py,70,W0621,Redefining name 'domain' from outer scope (line 26),,0,
354,r2/lib/template_helpers.py,135,W0621,Redefining name 'config' from outer scope (line 26),,0,
355,r2/lib/template_helpers.py,220,E0602,Undefined variable 'OrganicListing',,1,
356,r2/lib/template_helpers.py,362,W0621,Redefining name 'domain' from outer scope (line 26),,0,
357,r2/lib/template_helpers.py,377,W0621,Redefining name 'domain' from outer scope (line 26),,0,
358,r2/lib/template_helpers.py,376,W0622,Redefining built-in 'type',,0,
359,r2/lib/template_helpers.py,376,W0613,Unused argument 'context',,0,
360,r2/lib/template_helpers.py,471,W0621,Redefining name 'style_line' from outer scope (line 470),,0,
361,r2/lib/template_helpers.py,494,R0913,Too many arguments (6/5),,0,
362,r2/lib/template_helpers.py,495,W0621,Redefining name 'static' from outer scope (line 52),,0,
363,r2/lib/template_helpers.py,495,W0612,Unused variable 'static',,0,
366,r2/lib/filters.py,40,W0403,Relative import 'wrapped',should be 'r2.lib.wrapped',0,
367,r2/lib/filters.py,93,C0321,More than one statement on a single line,,1,Nothing at line 93
368,r2/lib/filters.py,93,R0904,Too many public methods (40/20),,1,
369,r2/lib/filters.py,157,W0231,__init__ method from base class 'ContentHandler' is not called,,0,
370,r2/lib/filters.py,160,W0613,Unused argument 'tagname',,0,
371,r2/lib/filters.py,241,R0914,Too many local variables (17/15),,1,Pylint is drunk
372,r2/lib/filters.py,272,W0106,"Expression ""[img_swap(image) for image in images]"" is assigned to nothing",,0,"But look at line 303 (Pylint is drunk), list is modified, but there's no reason to construct a list if it is not to return it !"
373,r2/lib/filters.py,281,W0106,"Expression ""[add_ext_to_link(a) for a in links]"" is assigned to nothing",,0,same as previous one
374,r2/lib/filters.py,294,R0914,Too many local variables (17/15),,0,Look at line 325
375,r2/lib/filters.py,357,C0322,Operator not preceded by a space,,0,Look at line 388
378,r2/lib/inventory.py,79,E1101,Instance of 'ScopedSession' has no 'query' member,,1,
379,r2/lib/inventory.py,100,R0914,Too many local variables (17/15),,0,
380,r2/lib/inventory.py,211,R0913,Too many arguments (6/5),,0,
381,r2/lib/inventory.py,211,R0914,Too many local variables (29/15),,0,
382,r2/lib/inventory.py,301,R0913,Too many arguments (6/5),,0,
383,r2/lib/rising.py,42,W0621,Redefining name 'count' from outer scope (line 28),,0,Bad smell
384,r2/lib/rising.py,65,W0612,Unused variable 'score',,1,Not really a way to avoid this... '_' can be used for translation...
385,r2/lib/rising.py,96,W0612,Unused variable 'score',,1,
386,r2/lib/rising.py,96,W0612,Unused variable 'norm_score',,1,
387,r2/lib/cssfilter.py,368,E1101,Instance of 'ValidationError' has no '_source_lines' member,,1,Comment at 364 explain how the variable is added
388,r2/lib/count.py,32,W0613,Unused argument 'wrapped',,0,
389,r2/lib/count.py,35,W0613,Unused argument 'sr',,0,
391,r2/lib/recommender.py,59,R0913,Too many arguments (6/5),,0,
392,r2/lib/recommender.py,124,R0914,Too many local variables (32/15),,0,
393,r2/lib/recommender.py,215,W0612,Unused variable 'score',,1,
394,r2/lib/recommender.py,279,R0913,Too many arguments (6/5),,0,
396,r2/lib/media.py,96,C0324,Comma not followed by a space,,0,
399,r2/lib/media.py,110,C0324,Comma not followed by a space,,0,
402,r2/lib/media.py,140,W0621,Redefining name 'gzip' from outer scope (line 36),,0,
403,r2/lib/media.py,215,E1101,Module 'hashlib' has no 'sha256' member,,1,
404,r2/lib/media.py,261,R0913,Too many arguments (7/5),,0,
405,r2/lib/media.py,261,R0914,Too many local variables (16/15),,0,
406,r2/lib/media.py,279,W0621,Redefining name 'thumbnail_url' from outer scope (line 203),,0,
407,r2/lib/media.py,396,R0913,Too many arguments (7/5),,0,
408,r2/lib/media.py,420,W0621,Redefining name 'thumbnail_url' from outer scope (line 203),,0,
409,r2/lib/media.py,423,W0612,Unused variable 'content_type',,0,
410,r2/lib/media.py,458,W0231,__init__ method from base class 'Scraper' is not called,,0,
411,r2/lib/media.py,462,W0621,Redefining name 'thumbnail_url' from outer scope (line 203),,0,
412,r2/lib/media.py,529,W0231,__init__ method from base class 'Scraper' is not called,,0,
413,r2/lib/media.py,566,W0621,Redefining name 'thumbnail_url' from outer scope (line 203),,0,
414,r2/lib/zookeeper.py,70,W0613,Unused argument 'stat',,0,
415,r2/lib/zookeeper.py,70,W0612,Unused variable 'watcher',,0,
416,r2/lib/zookeeper.py,86,R0913,Too many arguments (6/5),,0,
417,r2/lib/zookeeper.py,101,W0612,Unused variable 'watcher',,0,
418,r2/lib/zookeeper.py,108,W0622,Redefining built-in 'reduce',,0,
419,r2/lib/zookeeper.py,129,W0622,Redefining built-in 'reduce',,0,
420,r2/lib/zookeeper.py,166,W0613,Unused argument 'stat',,0,
421,r2/lib/zookeeper.py,166,W0612,Unused variable 'watcher',,0,
422,r2/lib/js.py,94,W0231,__init__ method from base class 'Source' is not called,,0,
423,r2/lib/js.py,134,W0231,__init__ method from base class 'Source' is not called,,0,
424,r2/lib/js.py,150,W0621,Redefining name 'module' from outer scope (line 396),,0,
425,r2/lib/js.py,193,W0231,__init__ method from base class 'Source' is not called,,0,
426,r2/lib/js.py,219,W0231,__init__ method from base class 'DataSource' is not called,,0,
427,r2/lib/js.py,249,W0621,Redefining name 'dependencies' from outer scope (line 558),,0,
428,r2/lib/js.py,282,W0231,__init__ method from base class 'LocaleSpecificSource' is not called,,0,
429,r2/lib/js.py,554,W0612,Unused variable 'm',,1,
433,r2/lib/sr_pops.py,32,C0324,Comma not followed by a space,,0,
436,r2/lib/lock.py,38,C0321,More than one statement on a single line,,0,
437,r2/lib/lock.py,40,R0902,Too many instance attributes (9/7),,0,
438,r2/lib/lock.py,45,R0913,Too many arguments (8/5),,0,
439,r2/lib/lock.py,62,W0622,Redefining built-in 'type',,0,
444,r2/lib/organic.py,65,W0612,Unused variable 'user_id',,0,
445,r2/lib/totp.py,35,W0621,Redefining name 'secret' from outer scope (line 70),,0,
446,r2/lib/totp.py,41,E1101,Module 'hashlib' has no 'sha1' member,,1,
447,r2/lib/totp.py,53,W0621,Redefining name 'secret' from outer scope (line 70),,0,
448,r2/lib/totp.py,63,W0622,Redefining built-in 'bytes',,0,
449,r2/lib/errors.py,231,W0621,Redefining name 'e' from outer scope (line 153),,1,Not the same scope
450,r2/lib/errors.py,246,R0901,Too many ancestors (9/7),,0,
451,r2/lib/errors.py,252,R0901,Too many ancestors (9/7),,0,
452,r2/lib/errors.py,286,C0321,More than one statement on a single line,,0,
453,r2/lib/plugin.py,110,W0703,Catching too general exception Exception,,0,
454,r2/lib/amqp.py,71,W0702,No exception type(s) specified,,0,
455,r2/lib/amqp.py,88,W0231,__init__ method from base class '_local' is not called,,0,
456,r2/lib/amqp.py,88,W0231,__init__ method from base class 'local' is not called,,0,
457,r2/lib/amqp.py,155,R0913,Too many arguments (6/5),,0,
458,r2/lib/amqp.py,179,W0703,Catching too general exception Exception,,0,
459,r2/lib/amqp.py,189,R0913,Too many arguments (6/5),,0,
460,r2/lib/amqp.py,254,R0913,Too many arguments (8/5),,0,
461,r2/lib/admin_utils.py,26,W0613,Unused argument 'test',,0,
462,r2/lib/admin_utils.py,26,W0613,Unused argument 'rand',,0,
463,r2/lib/admin_utils.py,30,W0622,Redefining built-in 'hash',,0,
464,r2/lib/admin_utils.py,30,W0613,Unused argument 'hash',,0,
465,r2/lib/admin_utils.py,30,W0613,Unused argument 'user',,0,
466,r2/lib/admin_utils.py,34,W0613,Unused argument 'loc',,0,
468,r2/lib/jsonresponse.py,82,W0613,Unused argument 'kw',,0,
469,r2/lib/jsonresponse.py,95,W0613,Unused argument 'a',,0,
470,r2/lib/jsonresponse.py,95,W0613,Unused argument 'action',,0,
471,r2/lib/jsonresponse.py,128,W0201,Attribute '_ratelimit' defined outside __init__,,0,
472,r2/lib/jsonresponse.py,52,W0201,Attribute '_data' defined outside __init__,,0,
473,r2/lib/jsonresponse.py,125,W0201,Attribute '_new_captcha' defined outside __init__,,0,
474,r2/lib/jsonresponse.py,49,W0201,Attribute '_errors' defined outside __init__,,0,
475,r2/lib/jsonresponse.py,156,W0201,Attribute 'objs' defined outside __init__,,0,
476,r2/lib/jsonresponse.py,125,W0201,Attribute '_new_captcha' defined outside __init__,,0,
477,r2/lib/jsonresponse.py,157,W0201,Attribute 'ops' defined outside __init__,,0,
481,r2/lib/base.py,29,W0403,Relative import 'utils',should be 'r2.lib.utils',0,
482,r2/lib/base.py,65,E0702,Raising NoneType while only classes,instances or string are allowed,1,Pylint does not do a lot of flow-control
483,r2/lib/base.py,97,E1101,Module 'hashlib' has no 'md5' member,,1,
484,r2/lib/base.py,139,C0321,More than one statement on a single line,,0,
485,r2/lib/base.py,140,C0321,More than one statement on a single line,,0,
486,r2/lib/base.py,212,R0913,Too many arguments (6/5),,1,
487,r2/lib/s3_helpers.py,111,E0602,Undefined variable 'logfile',,0,
488,r2/lib/comment_tree.py,61,W0621,Redefining name 'add_comments' from outer scope (line 51),,0,
489,r2/lib/comment_tree.py,77,W0702,No exception type(s) specified,,0,
490,r2/lib/comment_tree.py,149,W0612,Unused variable 'tree',,0,
491,r2/lib/comment_tree.py,127,W0612,Unused variable 'CommentSortsCache',,0,
492,r2/lib/comment_tree.py,150,W0612,Unused variable 'depth',,0,
493,r2/lib/comment_tree.py,237,W0612,Unused variable 'Account',,0,
494,r2/lib/comment_tree.py,437,C0324,Comma not followed by a space,,0,
499,r2/lib/comment_tree.py,429,W0612,Unused variable 'CommentSortsCache',,0,
500,r2/lib/stats.py,189,W0201,Attribute 'conn' defined outside __init__,,0,
501,r2/lib/stats.py,246,W0622,Redefining built-in 'type',,0,
502,r2/lib/stats.py,318,R0913,Too many arguments (6/5),,0,
503,r2/lib/stats.py,350,W0613,Unused argument 'cache_name',,0,
504,r2/lib/stats.py,370,W0612,Unused variable 'msg',,0,
505,r2/lib/stats.py,388,R0913,Too many arguments (6/5),,0,
506,r2/lib/stats.py,400,R0913,Too many arguments (7/5),,0,
507,r2/lib/stats.py,400,W0613,Unused argument 'cursor',,0,
508,r2/lib/stats.py,401,W0613,Unused argument 'executemany',,0,
509,r2/lib/stats.py,400,W0613,Unused argument 'parameters',,0,
510,r2/lib/stats.py,400,W0613,Unused argument 'statement',,0,
511,r2/lib/stats.py,400,W0613,Unused argument 'conn',,0,
512,r2/lib/stats.py,404,R0913,Too many arguments (7/5),,0,
513,r2/lib/stats.py,404,W0613,Unused argument 'cursor',,0,
514,r2/lib/stats.py,405,W0613,Unused argument 'executemany',,0,
515,r2/lib/stats.py,404,W0613,Unused argument 'parameters',,0,
516,r2/lib/stats.py,404,W0613,Unused argument 'statement',,0,
517,r2/lib/stats.py,404,W0613,Unused argument 'conn',,0,
518,r2/lib/stats.py,460,R0914,Too many local variables (16/15),,0,
519,r2/lib/stats.py,475,W0613,Unused argument 'kwargs',,0,
520,r2/lib/stats.py,461,W0612,Unused variable 'sep',,0,
521,r2/lib/stats.py,461,W0612,Unused variable 'port',,0,
522,r2/lib/emr_helpers.py,108,E1123,Passing unexpected keyword argument '_update' in function call,,1,
523,r2/lib/emr_helpers.py,154,R0902,Too many instance attributes (16/7),,0,
524,r2/lib/emr_helpers.py,155,R0913,Too many arguments (15/5),,0,
525,r2/lib/emr_helpers.py,155,W0102,Dangerous default value [] as argument,,0,
526,r2/lib/emr_helpers.py,155,W0102,Dangerous default value [] as argument,,0,
527,r2/lib/emr_helpers.py,155,W0102,Dangerous default value [] as argument,,0,
528,r2/lib/emr_helpers.py,212,W0231,__init__ method from base class 'Exception' is not called,,0,
529,r2/lib/permissions.py,26,R0904,Too many public methods (21/20),,0,
530,r2/lib/permissions.py,73,R0904,Too many public methods (21/20),,0,
531,r2/lib/merge.py,30,W0621,Redefining name 'original' from outer scope (line 71),,1,
532,r2/models/wiki.py,358,W0201,Attribute 'new_id' defined outside __init__,,0,
533,r2/lib/merge.py,38,W0621,Redefining name 'a' from outer scope (line 72),,1,
534,r2/lib/merge.py,38,W0621,Redefining name 'b' from outer scope (line 73),,1,
535,r2/lib/merge.py,46,W0621,Redefining name 'a' from outer scope (line 72),,1,
536,r2/lib/merge.py,46,W0621,Redefining name 'b' from outer scope (line 73),,1,
537,r2/lib/merge.py,46,W0621,Redefining name 'original' from outer scope (line 71),,1,
538,r2/lib/merge.py,66,W0232,Class has no __init__ method,,0,
540,r2/lib/log.py,140,W0612,Unused variable 'extra',,1,"Not used, but no way to avoid this"
541,r2/lib/strings.py,238,W0621,Redefining name 'plurals' from outer scope (line 258),,1,
542,r2/lib/strings.py,299,C0324,Comma not followed by a space,,0,
546,r2/lib/strings.py,327,W0613,Unused argument 'x',,0,
547,r2/lib/strings.py,364,W0612,Unused variable 'x',,0,
548,r2/lib/strings.py,433,W0622,Redefining built-in 'type',,0,
549,r2/lib/strings.py,424,W0612,Unused variable 'name',,0,
550,r2/lib/websockets.py,40,W0622,Redefining built-in 'type',,0,
551,r2/lib/websockets.py,66,E1101,Module 'hashlib' has no 'sha1' member,,1,
552,r2/lib/hardcachebackend.py,271,W0311,Bad indentation. Found 10 spaces,expected 12,0,
553,r2/lib/hardcachebackend.py,272,W0311,Bad indentation. Found 14 spaces,expected 16,0,
554,r2/lib/hardcachebackend.py,273,W0311,Bad indentation. Found 14 spaces,expected 16,0,
555,r2/lib/hardcachebackend.py,41,R0914,Too many local variables (18/15),,0,
556,r2/lib/hardcachebackend.py,44,W0621,Redefining name 'TZ' from outer scope (line 33),,0,
557,r2/lib/hardcachebackend.py,44,W0612,Unused variable 'TZ',,0,
558,r2/lib/hardcachebackend.py,91,W0622,Redefining built-in 'type',,0,
559,r2/lib/hardcachebackend.py,175,W0612,Unused variable 'rp',,0,
560,r2/lib/hardcachebackend.py,185,W0612,Unused variable 'e',,0,
561,r2/lib/hardcachebackend.py,227,W0622,Redefining built-in 'type',,0,
562,r2/lib/hardcachebackend.py,343,W0612,Unused variable 'e',,0,
564,r2/lib/captcha.py,38,W0221,Arguments number differs from overridden method,,0,
565,r2/lib/authentication.py,66,W0622,Redefining built-in 'hash',,0,
566,r2/lib/authentication.py,69,W0702,No exception type(s) specified,,0,
567,r2/lib/authentication.py,66,W0612,Unused variable 'hash',,0,
571,r2/lib/utils/_utils.so,1,E0611,No name '__class__' in module '__builtin__',,,
572,r2/lib/utils/_utils.so,1,E0611,No name '__new__' in module '__builtin__',,,
573,r2/lib/utils/_utils.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
578,r2/lib/pages/pages.py,4245,W0201,Attribute 'columns' defined outside __init__,,0,
579,r2/lib/utils/utils.py,150,W0621,Redefining name 'domain' from outer scope (line 166),,0,
580,r2/lib/utils/utils.py,172,W0621,Redefining name 'domain' from outer scope (line 166),,0,
581,r2/lib/utils/utils.py,217,W0702,No exception type(s) specified,,0,
582,r2/lib/utils/utils.py,198,W0612,Unused variable 'param_name',,0,
583,r2/lib/utils/utils.py,198,W0612,Unused variable 'sep',,0,
584,r2/lib/utils/utils.py,286,E1101,Instance of 'ParseResult' has no 'scheme' member,,0,
585,r2/lib/utils/utils.py,266,R0911,Too many return statements (10/6),,0,
586,r2/lib/utils/utils.py,348,W0621,Redefining name 'datetime' from outer scope (line 43),,0,
587,r2/lib/utils/utils.py,357,W0622,Redefining built-in 'dict',,0,
588,r2/lib/utils/utils.py,359,C0324,Comma not followed by a space,,0,
591,r2/lib/utils/utils.py,428,E1101,Instance of 'UrlParser' has no 'query' member,,0,
592,r2/lib/utils/utils.py,467,E1101,Instance of 'UrlParser' has no 'query' member,,0,
593,r2/lib/utils/utils.py,483,E1101,Instance of 'UrlParser' has no 'params' member,,0,
594,r2/lib/utils/utils.py,483,E1101,Instance of 'UrlParser' has no 'fragment' member,,0,
595,r2/lib/utils/utils.py,503,W0621,Redefining name 'g' from outer scope (line 44),,0,
596,r2/lib/utils/utils.py,503,W0404,Reimport 'g' (imported line 44),,0,
597,r2/lib/utils/utils.py,529,W0621,Redefining name 'g' from outer scope (line 44),,0,
598,r2/lib/utils/utils.py,529,W0404,Reimport 'g' (imported line 44),,0,
599,r2/lib/utils/utils.py,651,E1101,Instance of 'UrlParser' has no 'fragment' member,,0,
600,r2/lib/utils/utils.py,651,E1101,Instance of 'UrlParser' has no 'fragment' member,,0,
601,r2/lib/utils/utils.py,654,E1101,Instance of 'UrlParser' has no 'params' member,,0,
602,r2/lib/utils/utils.py,654,E1101,Instance of 'UrlParser' has no 'query' member,,0,
603,r2/lib/utils/utils.py,598,W0201,Attribute 'path' defined outside __init__,,0,
604,r2/controllers/reddit_base.py,717,W0201,Attribute 'scheme' defined outside __init__,,0,
605,r2/lib/utils/utils.py,589,W0201,Attribute 'port' defined outside __init__,,0,
606,r2/lib/utils/utils.py,709,W0622,Redefining built-in 'id',,0,
607,r2/lib/utils/utils.py,700,C0324,Comma not followed by a space,,0,
610,r2/lib/utils/utils.py,708,C0324,Comma not followed by a space,,0,
613,r2/lib/utils/utils.py,709,C0324,Comma not followed by a space,,0,
616,r2/lib/utils/utils.py,719,W0621,Redefining name 'cols' from outer scope (line 713),,0,
617,r2/lib/utils/utils.py,724,C0324,Comma not followed by a space,,0,
620,r2/lib/utils/utils.py,757,W0631,Using possibly undefined loop variable 't',,1,things cannot be empty. Bad flow control
621,r2/lib/utils/utils.py,853,W0621,Redefining name 'g' from outer scope (line 44),,0,
622,r2/lib/utils/utils.py,853,W0404,Reimport 'g' (imported line 44),,0,
623,r2/lib/utils/utils.py,869,C0322,Operator not preceded by a space,,0,
626,r2/lib/utils/utils.py,869,E0602,Undefined variable 'time',,0,
627,r2/lib/utils/utils.py,870,C0322,Operator not preceded by a space,,0,
630,r2/lib/utils/utils.py,871,C0324,Comma not followed by a space,,0,
633,r2/lib/utils/utils.py,871,E0602,Undefined variable 'time',,0,
634,r2/lib/utils/utils.py,875,C0324,Comma not followed by a space,,0,
637,r2/lib/utils/utils.py,926,C0324,Comma not followed by a space,,0,
640,r2/lib/utils/utils.py,927,C0324,Comma not followed by a space,,0,
643,r2/lib/utils/utils.py,952,R0913,Too many arguments (7/5),,0,
644,r2/lib/utils/utils.py,952,R0914,Too many local variables (18/15),,0,
645,r2/lib/utils/utils.py,1001,W0613,Unused argument 'frame',,0,
646,r2/lib/utils/utils.py,1001,W0613,Unused argument 'signum',,0,
647,r2/lib/utils/utils.py,1066,R0914,Too many local variables (28/15),,0,
648,r2/lib/utils/utils.py,1071,W0621,Redefining name 'datetime' from outer scope (line 43),,0,
649,r2/lib/utils/utils.py,1071,W0404,Reimport 'datetime' (imported line 43),,0,
650,r2/lib/utils/utils.py,1082,W0702,No exception type(s) specified,,0,
651,r2/lib/utils/utils.py,1162,C0324,Comma not followed by a space,,0,
654,r2/lib/utils/utils.py,1171,W0631,Using possibly undefined loop variable 'item',,1,
655,r2/lib/utils/utils.py,1066,R0912,Too many branches (26/25),,0,
656,r2/lib/utils/utils.py,1207,E0710,Raising a new style class which doesn't inherit from BaseException,,0,
657,r2/lib/utils/utils.py,1211,E0710,Raising a new style class which doesn't inherit from BaseException,,0,
658,r2/lib/utils/utils.py,1215,E0710,Raising a new style class which doesn't inherit from BaseException,,0,
659,r2/controllers/reddit_base.py,1124,W0201,Attribute 'name' defined outside __init__,,0,
660,r2/lib/utils/utils.py,1237,W0702,No exception type(s) specified,,0,
661,r2/lib/utils/utils.py,1248,W0621,Redefining name 'traceback' from outer scope (line 25),,0,
662,r2/lib/utils/utils.py,1257,W0621,Redefining name 'lineno' from outer scope (line 872),,0,
663,r2/lib/utils/utils.py,1249,W0621,Redefining name 'datetime' from outer scope (line 43),,0,
664,r2/lib/utils/utils.py,1248,W0404,Reimport 'traceback' (imported line 25),,0,
665,r2/lib/utils/utils.py,1249,W0404,Reimport 'datetime' (imported line 43),,0,
666,r2/lib/utils/utils.py,1247,W0613,Unused argument 'a',,0,
667,r2/lib/utils/utils.py,1315,W0612,Unused variable 'rest',,0,
668,r2/lib/utils/utils.py,1315,W0612,Unused variable 'sep',,0,
669,r2/lib/utils/utils.py,1430,W0613,Unused argument 'data',,0,
670,r2/lib/utils/utils.py,1430,W0613,Unused argument 'key',,0,
671,r2/lib/utils/utils.py,1449,W0621,Redefining name 'domain' from outer scope (line 166),,0,
672,r2/lib/utils/utils.py,1512,W0622,Redefining built-in 'next',,0,
674,r2/lib/utils/__init__.py,23,W0403,Relative import 'utils',should be 'r2.lib.utils.utils',0,
676,r2/lib/utils/__init__.py,24,W0403,Relative import 'http_utils',should be 'r2.lib.utils.http_utils',0,
678,r2/lib/utils/__init__.py,25,W0403,Relative import 'thing_utils',should be 'r2.lib.utils.thing_utils',0,
680,r2/lib/utils/thing_utils.py,24,W0403,Relative import 'utils',should be 'r2.lib.utils.utils',0,
681,r2/lib/contrib/rcssmin.py,100,F0401,Unable to import '_rcssmin',,0,This script is available in C for a gain factor of 50
682,r2/lib/contrib/ipaddress.py,716,W0311,Bad indentation. Found 10 spaces,expected 12,0,
683,r2/lib/contrib/ipaddress.py,1126,W0311,Bad indentation. Found 7 spaces,expected 8,0,
684,r2/lib/contrib/ipaddress.py,1133,W0311,Bad indentation. Found 7 spaces,expected 8,0,
685,r2/lib/contrib/ipaddress.py,1134,W0311,Bad indentation. Found 7 spaces,expected 8,0,
686,r2/lib/contrib/ipaddress.py,1135,W0311,Bad indentation. Found 11 spaces,expected 12,0,
687,r2/lib/contrib/ipaddress.py,1136,W0311,Bad indentation. Found 7 spaces,expected 8,0,
690,r2/lib/contrib/ipaddress.py,281,W0612,Unused variable 'networks',,0,
691,r2/lib/contrib/ipaddress.py,446,E1101,Instance of '_IPAddressBase' has no '_explode_shorthand_ip_string' member,,,
692,r2/lib/contrib/ipaddress.py,464,E1101,Instance of '_IPAddressBase' has no '_prefixlen' member,,,
693,r2/lib/contrib/ipaddress.py,465,E1101,Instance of '_IPAddressBase' has no '_ALL_ONES' member,,,
694,r2/lib/contrib/ipaddress.py,465,E1101,Instance of '_IPAddressBase' has no '_ALL_ONES' member,,,
695,r2/lib/contrib/ipaddress.py,497,E1101,Instance of '_IPAddressBase' has no '_prefixlen' member,,,
696,r2/lib/contrib/ipaddress.py,498,E1101,Instance of '_IPAddressBase' has no '_string_from_ip_int' member,,,
697,r2/lib/contrib/ipaddress.py,510,W0231,__init__ method from base class '_IPAddressBase' is not called,,,
698,r2/lib/contrib/ipaddress.py,516,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
699,r2/lib/contrib/ipaddress.py,519,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
700,r2/lib/contrib/ipaddress.py,522,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
701,r2/lib/contrib/ipaddress.py,526,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
702,r2/lib/contrib/ipaddress.py,527,E1101,Instance of '_BaseAddress' has no '_version' member,,,
703,r2/lib/contrib/ipaddress.py,550,E1101,Instance of '_BaseAddress' has no '_version' member,,,
704,r2/lib/contrib/ipaddress.py,556,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
705,r2/lib/contrib/ipaddress.py,557,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
706,r2/lib/contrib/ipaddress.py,561,E1101,Instance of '_BaseAddress' has no '_version' member,,,
707,r2/lib/contrib/ipaddress.py,567,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
708,r2/lib/contrib/ipaddress.py,568,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
709,r2/lib/contrib/ipaddress.py,576,E1101,Instance of '_BaseAddress' has no '_version' member,,,
710,r2/lib/contrib/ipaddress.py,581,E1101,Instance of '_BaseAddress' has no '_version' member,,,
711,r2/lib/contrib/ipaddress.py,587,E1101,Instance of '_BaseAddress' has no '_string_from_ip_int' member,,,
712,r2/lib/contrib/ipaddress.py,587,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
713,r2/lib/contrib/ipaddress.py,590,E1101,Instance of '_BaseAddress' has no '_ip' member,,,
714,r2/lib/contrib/ipaddress.py,593,E1101,Instance of '_BaseAddress' has no '_version' member,,,
715,r2/lib/contrib/ipaddress.py,609,W0231,__init__ method from base class '_IPAddressBase' is not called,,,
716,r2/lib/contrib/ipaddress.py,609,W0613,Unused argument 'address',,,
717,r2/lib/contrib/ipaddress.py,613,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
718,r2/lib/contrib/ipaddress.py,616,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
719,r2/lib/contrib/ipaddress.py,628,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
720,r2/lib/contrib/ipaddress.py,632,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
721,r2/lib/contrib/ipaddress.py,635,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
722,r2/lib/contrib/ipaddress.py,639,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
723,r2/lib/contrib/ipaddress.py,642,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
724,r2/lib/contrib/ipaddress.py,647,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
725,r2/lib/contrib/ipaddress.py,652,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
726,r2/lib/contrib/ipaddress.py,655,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
727,r2/lib/contrib/ipaddress.py,661,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
728,r2/lib/contrib/ipaddress.py,662,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
729,r2/lib/contrib/ipaddress.py,663,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
730,r2/lib/contrib/ipaddress.py,664,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
731,r2/lib/contrib/ipaddress.py,668,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
732,r2/lib/contrib/ipaddress.py,674,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
733,r2/lib/contrib/ipaddress.py,675,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
734,r2/lib/contrib/ipaddress.py,676,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
735,r2/lib/contrib/ipaddress.py,677,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
736,r2/lib/contrib/ipaddress.py,696,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
737,r2/lib/contrib/ipaddress.py,697,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
738,r2/lib/contrib/ipaddress.py,698,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
739,r2/lib/contrib/ipaddress.py,707,E1101,Instance of '_BaseNetwork' has no 'ip' member,,,
740,r2/lib/contrib/ipaddress.py,708,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
741,r2/lib/contrib/ipaddress.py,711,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
742,r2/lib/contrib/ipaddress.py,711,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
743,r2/lib/contrib/ipaddress.py,715,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
744,r2/lib/contrib/ipaddress.py,723,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
745,r2/lib/contrib/ipaddress.py,728,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
746,r2/lib/contrib/ipaddress.py,737,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
747,r2/lib/contrib/ipaddress.py,738,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
748,r2/lib/contrib/ipaddress.py,746,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
749,r2/lib/contrib/ipaddress.py,746,E1101,Instance of '_BaseNetwork' has no '_ALL_ONES' member,,,
750,r2/lib/contrib/ipaddress.py,747,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
751,r2/lib/contrib/ipaddress.py,753,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
752,r2/lib/contrib/ipaddress.py,758,E1101,Instance of '_BaseNetwork' has no 'ip' member,,,
753,r2/lib/contrib/ipaddress.py,758,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
754,r2/lib/contrib/ipaddress.py,762,E1101,Instance of '_BaseNetwork' has no 'ip' member,,,
755,r2/lib/contrib/ipaddress.py,762,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
756,r2/lib/contrib/ipaddress.py,766,E1101,Instance of '_BaseNetwork' has no 'ip' member,,,
757,r2/lib/contrib/ipaddress.py,771,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
758,r2/lib/contrib/ipaddress.py,779,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
759,r2/lib/contrib/ipaddress.py,817,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
760,r2/lib/contrib/ipaddress.py,824,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
761,r2/lib/contrib/ipaddress.py,831,W0612,Unused variable 'ret_addrs',,,
762,r2/lib/contrib/ipaddress.py,896,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
763,r2/lib/contrib/ipaddress.py,900,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
764,r2/lib/contrib/ipaddress.py,902,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
765,r2/lib/contrib/ipaddress.py,905,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
766,r2/lib/contrib/ipaddress.py,907,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
767,r2/lib/contrib/ipaddress.py,919,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
768,r2/lib/contrib/ipaddress.py,919,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
769,r2/lib/contrib/ipaddress.py,919,E1101,Instance of '_BaseNetwork' has no 'netmask' member,,,
770,r2/lib/contrib/ipaddress.py,947,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
771,r2/lib/contrib/ipaddress.py,947,E1101,Instance of '_BaseNetwork' has no '_max_prefixlen' member,,,
772,r2/lib/contrib/ipaddress.py,952,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
773,r2/lib/contrib/ipaddress.py,956,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
774,r2/lib/contrib/ipaddress.py,960,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
775,r2/lib/contrib/ipaddress.py,962,E1101,Instance of '_BaseNetwork' has no '_is_valid_netmask' member,,,
776,r2/lib/contrib/ipaddress.py,967,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
777,r2/lib/contrib/ipaddress.py,968,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
778,r2/lib/contrib/ipaddress.py,969,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
779,r2/lib/contrib/ipaddress.py,977,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
780,r2/lib/contrib/ipaddress.py,979,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
781,r2/lib/contrib/ipaddress.py,985,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
782,r2/lib/contrib/ipaddress.py,985,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
783,r2/lib/contrib/ipaddress.py,986,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
784,r2/lib/contrib/ipaddress.py,1009,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
785,r2/lib/contrib/ipaddress.py,1013,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
786,r2/lib/contrib/ipaddress.py,1017,E1101,Instance of '_BaseNetwork' has no '_prefixlen' member,,,
787,r2/lib/contrib/ipaddress.py,1025,E1101,Instance of '_BaseNetwork' has no 'network_address' member,,,
788,r2/lib/contrib/ipaddress.py,1027,E1101,Instance of '_BaseNetwork' has no '_version' member,,,
789,r2/lib/contrib/ipaddress.py,1045,W0613,Unused argument 'address',,,
790,r2/lib/contrib/ipaddress.py,1111,W0612,Unused variable '_',,,
791,r2/lib/contrib/ipaddress.py,1136,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
792,r2/lib/contrib/ipaddress.py,1137,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
793,r2/lib/contrib/ipaddress.py,1154,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
794,r2/lib/contrib/ipaddress.py,1155,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
795,r2/lib/contrib/ipaddress.py,1156,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
796,r2/lib/contrib/ipaddress.py,1157,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
797,r2/lib/contrib/ipaddress.py,1158,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
798,r2/lib/contrib/ipaddress.py,1159,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
799,r2/lib/contrib/ipaddress.py,1173,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
800,r2/lib/contrib/ipaddress.py,1174,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
801,r2/lib/contrib/ipaddress.py,1188,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
802,r2/lib/contrib/ipaddress.py,1188,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
803,r2/lib/contrib/ipaddress.py,1203,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
804,r2/lib/contrib/ipaddress.py,1204,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
805,r2/lib/contrib/ipaddress.py,1217,E1101,Instance of '_BaseV4' has no 'network_address' member,,,
806,r2/lib/contrib/ipaddress.py,1218,E1101,Instance of '_BaseV4' has no 'broadcast_address' member,,,
807,r2/lib/contrib/ipaddress.py,1376,R0904,Too many public methods (26/20),,0,
808,r2/lib/contrib/ipaddress.py,1580,W0613,Unused argument 'address',,,
809,r2/lib/contrib/ipaddress.py,1747,E1101,Instance of '_BaseV6' has no '_ip' member,,,
810,r2/lib/contrib/ipaddress.py,1771,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
811,r2/lib/contrib/ipaddress.py,1773,E1101,Instance of '_BaseV6' has no 'ip' member,,,
812,r2/lib/contrib/ipaddress.py,1784,E1101,Instance of '_BaseV6' has no 'prefixlen' member,,,
813,r2/lib/contrib/ipaddress.py,1779,W0612,Unused variable 'i',,,
814,r2/lib/contrib/ipaddress.py,1794,E1101,Instance of '_BaseV6' has no '_ip' member,,,
815,r2/lib/contrib/ipaddress.py,1812,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
816,r2/lib/contrib/ipaddress.py,1813,E1101,Instance of '_BaseV6' has no 'broadcast_address' member,,,
817,r2/lib/contrib/ipaddress.py,1835,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
818,r2/lib/contrib/ipaddress.py,1836,E1101,Instance of '_BaseV6' has no 'broadcast_address' member,,,
819,r2/lib/contrib/ipaddress.py,1849,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
820,r2/lib/contrib/ipaddress.py,1850,E1101,Instance of '_BaseV6' has no 'broadcast_address' member,,,
821,r2/lib/contrib/ipaddress.py,1867,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
822,r2/lib/contrib/ipaddress.py,1868,E1101,Instance of '_BaseV6' has no 'broadcast_address' member,,,
823,r2/lib/contrib/ipaddress.py,1881,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
824,r2/lib/contrib/ipaddress.py,1882,E1101,Instance of '_BaseV6' has no 'broadcast_address' member,,,
825,r2/lib/contrib/ipaddress.py,1894,E1101,Instance of '_BaseV6' has no '_ip' member,,,
826,r2/lib/contrib/ipaddress.py,1896,E1101,Instance of '_BaseV6' has no '_ip' member,,,
827,r2/lib/contrib/ipaddress.py,1908,E1101,Instance of '_BaseV6' has no '_ip' member,,,
828,r2/lib/contrib/ipaddress.py,1910,E1101,Instance of '_BaseV6' has no '_ip' member,,,
829,r2/lib/contrib/ipaddress.py,1911,E1101,Instance of '_BaseV6' has no '_ip' member,,,
830,r2/lib/contrib/ipaddress.py,1922,E1101,Instance of '_BaseV6' has no '_ip' member,,,
831,r2/lib/contrib/ipaddress.py,1924,E1101,Instance of '_BaseV6' has no '_ip' member,,,
832,r2/lib/contrib/ipaddress.py,1936,E1101,Instance of '_BaseV6' has no 'network_address' member,,,
833,r2/lib/contrib/ipaddress.py,1938,E1101,Instance of '_BaseV6' has no '_ip' member,,,
834,r2/lib/contrib/ipaddress.py,1950,E1101,Instance of '_BaseV6' has no 'network' member,,,
835,r2/lib/contrib/ipaddress.py,1953,E1101,Instance of '_BaseV6' has no 'network' member,,,
836,r2/lib/contrib/ipaddress.py,1955,E1101,Instance of '_BaseV6' has no '_ip' member,,,
837,r2/lib/contrib/ipaddress.py,2192,E0102,method already defined line 2184,,0,with_netmask is defined twice.. Really strange ! Pylint 1 - Reddit 0
838,r2/lib/contrib/ipaddress.py,2057,R0904,Too many public methods (30/20),,,
839,r2/lib/providers/__init__.py,23,W0622,Redefining built-in 'type',,0,
840,r2/lib/providers/media/s3.py,76,W0612,Unused variable 'encoding',,0,
841,r2/lib/manager/db_manager.py,37,R0913,Too many arguments (8/5),,,
842,r2/lib/manager/db_manager.py,82,W0613,Unused argument 'kw',,0,
843,r2/lib/manager/db_manager.py,88,R0913,Too many arguments (6/5),,,
844,r2/lib/manager/db_manager.py,88,W0613,Unused argument 'kw',,0,
845,r2/lib/manager/db_manager.py,111,W0613,Unused argument 'g_override',,0,
846,r2/lib/manager/db_manager.py,123,W0703,Catching too general exception Exception,,0,
847,r2/lib/manager/tp_manager.py,55,E1101,Module 'hashlib' has no 'sha1' member,,1,
848,r2/lib/validator/__init__.py,25,W0403,Relative import 'validator',should be 'r2.lib.validator.validator',0,
851,r2/lib/validator/validator.py,1342,W0311,Bad indentation. Found 19 spaces,expected 20,0,
852,r2/lib/validator/validator.py,1344,W0311,Bad indentation. Found 19 spaces,expected 20,0,
858,r2/lib/validator/validator.py,78,R0902,Too many instance attributes (8/7),,0,
859,r2/lib/validator/validator.py,81,R0913,Too many arguments (8/5),,0,
860,r2/lib/validator/validator.py,93,W0102,Dangerous default value {} as argument,,0,
861,r2/lib/validator/validator.py,131,E1101,Instance of 'Validator' has no 'run' member,,0,
862,r2/lib/validator/validator.py,276,W0613,Unused argument 'param_vals',,0,
863,r2/lib/validator/validator.py,276,W0613,Unused argument 'responder',,0,
864,r2/lib/validator/validator.py,276,W0613,Unused argument 'simple_vals',,0,
865,r2/lib/validator/validator.py,281,W0613,Unused argument 'param_vals',,0,
866,r2/lib/validator/validator.py,281,W0613,Unused argument 'responder',,0,
867,r2/lib/validator/validator.py,281,W0613,Unused argument 'simple_vals',,0,
868,r2/lib/validator/validator.py,285,W0613,Unused argument 'param_vals',,0,
869,r2/lib/validator/validator.py,285,W0613,Unused argument 'simple_vals',,0,
870,r2/lib/validator/validator.py,381,C0321,More than one statement on a single line,,0,
871,r2/lib/validator/validator.py,650,R0913,Too many arguments (6/5),,0,
872,r2/lib/validator/validator.py,709,W0612,Unused variable 'a',,0,
873,r2/lib/validator/validator.py,780,C0321,More than one statement on a single line,,0,
874,r2/lib/validator/validator.py,815,R0913,Too many arguments (8/5),,0,
875,r2/lib/validator/validator.py,882,C0321,More than one statement on a single line,,0,
876,r2/lib/validator/validator.py,950,W0621,Redefining name 'VModhash' from outer scope (line 916),,0,
877,r2/lib/validator/validator.py,960,W0613,Unused argument 'vh',,0,
878,r2/lib/validator/validator.py,974,W0232,Class has no __init__ method,,0,
879,r2/lib/validator/validator.py,988,W0621,Redefining name 'VModhash' from outer scope (line 916),,0,
880,r2/lib/validator/validator.py,977,E1002,Use of super on an old style class,,1,It's not old syntax at all :/
881,r2/lib/validator/validator.py,997,W0221,Arguments number differs from overridden method,,0,
882,r2/lib/validator/validator.py,1004,W0221,Arguments number differs from overridden method,,0,
883,r2/lib/validator/validator.py,1016,W0221,Arguments number differs from overridden method,,0,
884,r2/lib/validator/validator.py,1016,W0613,Unused argument 'link_id',,0,
885,r2/lib/validator/validator.py,1034,W0221,Arguments number differs from overridden method,,0,
886,r2/lib/validator/validator.py,1089,W0221,Arguments number differs from overridden method,,0,
887,r2/lib/validator/validator.py,1158,W0221,Arguments number differs from overridden method,,0,
888,r2/lib/validator/validator.py,1209,R0911,Too many return statements (7/6),,0,
889,r2/lib/validator/validator.py,1246,W0221,Arguments number differs from overridden method,,0,
890,r2/lib/validator/validator.py,1362,W0221,Arguments number differs from overridden method,,0,
891,r2/lib/validator/validator.py,1459,W0621,Redefining name 'domain' from outer scope (line 39),,0,
892,r2/lib/validator/validator.py,1545,R0913,Too many arguments (7/5),,0,
893,r2/lib/validator/validator.py,1545,W0622,Redefining built-in 'min',,0,
894,r2/lib/validator/validator.py,1545,W0622,Redefining built-in 'max',,0,
895,r2/lib/validator/validator.py,1545,W0622,Redefining built-in 'coerce',,0,
896,r2/lib/validator/validator.py,1560,W0622,Redefining built-in 'range',,0,
897,r2/lib/validator/validator.py,1700,W0621,Redefining name 'time' from outer scope (line 39),,0,
898,r2/lib/validator/validator.py,1683,W0621,Redefining name 'admin_ratelimit' from outer scope (line 39),,0,
899,r2/lib/validator/validator.py,1707,W0621,Redefining name 'datetime' from outer scope (line 39),,0,
900,r2/lib/validator/validator.py,1718,C0202,Class method should have 'cls' as first argument,,0,
901,r2/lib/validator/validator.py,1742,W0621,Redefining name 'time' from outer scope (line 39),,0,
902,r2/lib/validator/validator.py,1750,C0202,Class method should have 'cls' as first argument,,0,
903,r2/lib/validator/validator.py,2047,W0621,Redefining name 'domain' from outer scope (line 39),,0,
904,r2/lib/validator/validator.py,2077,R0913,Too many arguments (8/5),,0,
905,r2/lib/validator/validator.py,2081,W0622,Redefining built-in 'format',,0,
906,r2/lib/validator/validator.py,2196,W0221,Arguments number differs from overridden method,,0,
907,r2/lib/validator/validator.py,2200,R0913,Too many arguments (10/5),,0,
908,r2/lib/validator/validator.py,2245,W0221,Arguments number differs from overridden method,,0,
909,r2/lib/validator/validator.py,2494,W0622,Redefining built-in 'type',,0,
910,r2/lib/validator/validator.py,2596,W0221,Arguments number differs from overridden method,,0,
911,r2/lib/validator/validator.py,2637,C0202,Class method should have 'cls' as first argument,,0,
912,r2/lib/validator/validator.py,2648,W0612,Unused variable 'user',,0,
913,r2/lib/validator/wiki.py,59,R0911,Too many return statements (16/6),,0,
914,r2/lib/validator/wiki.py,195,W0221,Arguments number differs from overridden method,,0,
915,r2/lib/validator/wiki.py,231,R0913,Too many arguments (6/5),,0,
916,r2/lib/validator/wiki.py,288,W0221,Arguments number differs from overridden method,,0,
917,r2/lib/validator/wiki.py,304,W0221,Arguments number differs from overridden method,,0,
918,r2/lib/validator/wiki.py,331,W0221,Arguments number differs from overridden method,,0,
919,r2/lib/validator/wiki.py,331,R0911,Too many return statements (7/6),,0,
920,r2/lib/validator/wiki.py,353,W0221,Arguments number differs from overridden method,,0,
926,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__class__' in module '__builtin__',,,
927,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__new__' in module '__builtin__',,,
928,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
929,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__class__' in module '__builtin__',,,
930,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__new__' in module '__builtin__',,,
931,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
932,r2/lib/mr_tools/_mr_tools.so,1,W0232,Class has no __init__ method,,1,
933,r2/lib/mr_tools/_mr_tools.so,1,W0232,Class has no __init__ method,,1,
934,r2/lib/mr_tools/_mr_tools.so,1,W0232,Class has no __init__ method,,1,
935,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__class__' in module '__builtin__',,,
936,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__new__' in module '__builtin__',,,
937,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
938,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__class__' in module '__builtin__',,,
939,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__new__' in module '__builtin__',,,
940,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
941,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__class__' in module '__builtin__',,,
942,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__new__' in module '__builtin__',,,
943,r2/lib/mr_tools/_mr_tools.so,1,E0611,No name '__subclasshook__' in module '__builtin__',,,
944,r2/lib/mr_tools/mr_tools.py,77,E0711,NotImplemented raised - should raise NotImplementedError,,0,convention de nommage
945,r2/lib/mr_tools/mr_tools.py,76,W0613,Unused argument 'values',,0,
946,r2/lib/mr_tools/mr_tools.py,94,E0602,Undefined variable 'process',,0,
947,r2/lib/pages/__init__.py,23,W0403,Relative import 'pages',should be 'r2.lib.pages.pages',0,
949,r2/lib/pages/__init__.py,24,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
951,r2/lib/pages/pages.py,3626,W0311,Bad indentation. Found 13 spaces,expected 12,0,
952,r2/lib/pages/pages.py,4460,W0311,Bad indentation. Found 3 spaces,expected 4,0,
953,r2/lib/pages/pages.py,4461,W0311,Bad indentation. Found 7 spaces,expected 8,0,
954,r2/lib/pages/pages.py,4463,W0311,Bad indentation. Found 3 spaces,expected 4,0,
955,r2/lib/pages/pages.py,4464,W0311,Bad indentation. Found 7 spaces,expected 8,0,
960,r2/lib/pages/pages.py,155,W0613,Unused argument 'account_id',,0,
961,r2/lib/pages/pages.py,158,W0403,Relative import 'things',should be 'r2.lib.pages.things',0,
962,r2/lib/pages/pages.py,195,R0902,Too many instance attributes (23/7),,0,
963,r2/lib/pages/pages.py,232,R0913,Too many arguments (19/5),,0,
964,r2/lib/pages/pages.py,232,R0914,Too many local variables (24/15),,0,
965,r2/lib/pages/pages.py,232,W0613,Unused argument 'loginbox',,0,
966,r2/lib/pages/pages.py,460,R0914,Too many local variables (30/15),,0,
967,r2/lib/pages/pages.py,607,W0621,Redefining name 'menu' from outer scope (line 115),,0,
968,r2/lib/pages/pages.py,487,W0404,Reimport 'AdminNotesSidebar' (imported line 482),,0,
969,r2/lib/pages/pages.py,460,R0912,Too many branches (48/25),,0,
970,r2/lib/pages/pages.py,829,W0702,No exception type(s) specified,,0,
971,r2/lib/pages/pages.py,838,W0231,__init__ method from base class 'Templated' is not called,,0,
972,r2/lib/pages/pages.py,993,R0913,Too many arguments (9/5),,0,
973,r2/lib/pages/pages.py,1004,R0913,Too many arguments (11/5),,0,
974,r2/lib/pages/pages.py,1004,W0102,Dangerous default value [] as argument,,0,
975,r2/lib/pages/pages.py,1142,R0913,Too many arguments (6/5),,0,
976,r2/lib/pages/pages.py,1166,C0322,Operator not preceded by a space,,0,
979,r2/lib/pages/pages.py,1191,W0105,String statement has no effect,,0,
980,r2/lib/pages/pages.py,1200,W0105,String statement has no effect,,0,
981,r2/lib/pages/pages.py,1284,R0913,Too many arguments (6/5),,0,
982,r2/lib/pages/pages.py,1309,R0913,Too many arguments (13/5),,0,
983,r2/lib/pages/pages.py,1309,W0102,Dangerous default value {} as argument,,0,
984,r2/lib/pages/pages.py,1309,W0102,Dangerous default value {} as argument,,0,
985,r2/lib/pages/pages.py,1364,R0902,Too many instance attributes (8/7),,0,
986,r2/lib/pages/pages.py,1378,R0913,Too many arguments (7/5),,0,
987,r2/lib/pages/pages.py,1378,R0914,Too many local variables (19/15),,0,
988,r2/lib/pages/pages.py,1492,W0613,Unused argument 'meta_description',,0,
989,r2/lib/pages/pages.py,1539,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
990,r2/lib/pages/pages.py,1557,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
991,r2/lib/pages/pages.py,1613,R0913,Too many arguments (6/5),,0,
992,r2/lib/pages/pages.py,1613,R0914,Too many local variables (25/15),,0,
993,r2/lib/pages/pages.py,1613,W0231,__init__ method from base class 'Templated' is not called,,0,
994,r2/lib/pages/pages.py,1745,W0613,Unused argument 'a',,0,
995,r2/lib/pages/pages.py,1745,W0613,Unused argument 'kw',,0,
996,r2/lib/pages/pages.py,1761,C0322,Operator not preceded by a space,,0,
999,r2/lib/pages/pages.py,1764,W0621,Redefining name 'menu' from outer scope (line 115),,0,
1000,r2/lib/pages/pages.py,1764,W0404,Reimport 'menu' (imported line 115),,0,
1001,r2/lib/pages/pages.py,1792,R0913,Too many arguments (8/5),,0,
1002,r2/lib/pages/pages.py,1792,W0102,Dangerous default value {} as argument,,0,
1003,r2/lib/pages/pages.py,1794,W0613,Unused argument 'search_params',,0,
1004,r2/lib/pages/pages.py,1896,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
1005,r2/lib/pages/pages.py,1933,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
1006,r2/lib/pages/pages.py,1938,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
1007,r2/lib/pages/pages.py,1995,R0902,Too many instance attributes (10/7),,0,
1008,r2/lib/pages/pages.py,2110,W0102,Dangerous default value [] as argument,,0,
1009,r2/lib/pages/pages.py,2136,C0321,More than one statement on a single line,,0,
1010,r2/lib/pages/pages.py,2146,R0913,Too many arguments (6/5),,0,
1011,r2/lib/pages/pages.py,2424,W0621,Redefining name 'media' from outer scope (line 99),,0,
1012,r2/lib/pages/pages.py,2460,R0913,Too many arguments (6/5),,0,
1013,r2/lib/pages/pages.py,2460,C0324,Comma not followed by a space,,0,
1016,r2/lib/pages/pages.py,2460,W0102,Dangerous default value {} as argument,,0,
1017,r2/lib/pages/pages.py,2487,R0913,Too many arguments (10/5),,0,
1018,r2/lib/pages/pages.py,2511,R0913,Too many arguments (11/5),,0,
1019,r2/lib/pages/pages.py,2511,R0914,Too many local variables (24/15),,0,
1020,r2/lib/pages/pages.py,2604,W0622,Redefining built-in 'format',,0,
1021,r2/lib/pages/pages.py,2511,R0912,Too many branches (37/25),,0,
1022,r2/lib/pages/pages.py,2755,R0913,Too many arguments (7/5),,0,
1023,r2/lib/pages/pages.py,2755,W0102,Dangerous default value [] as argument,,0,
1024,r2/lib/pages/pages.py,2755,W0102,Dangerous default value [] as argument,,0,
1025,r2/lib/pages/pages.py,2782,R0913,Too many arguments (8/5),,0,
1026,r2/lib/pages/pages.py,2782,W0102,Dangerous default value {} as argument,,0,
1027,r2/lib/pages/pages.py,2797,R0913,Too many arguments (15/5),,0,
1028,r2/lib/pages/pages.py,2797,R0914,Too many local variables (16/15),,0,
1029,r2/lib/pages/pages.py,2797,W0102,Dangerous default value {} as argument,,0,
1030,r2/lib/pages/pages.py,2797,W0102,Dangerous default value {} as argument,,0,
1031,r2/lib/pages/pages.py,2797,W0613,Unused argument 'kw',,0,
1032,r2/lib/pages/pages.py,2831,R0902,Too many instance attributes (10/7),,0,
1033,r2/lib/pages/pages.py,2839,W0613,Unused argument 'kw',,0,
1034,r2/lib/pages/pages.py,2890,R0902,Too many instance attributes (9/7),,0,
1035,r2/lib/pages/pages.py,2892,R0913,Too many arguments (12/5),,0,
1036,r2/lib/pages/pages.py,2892,R0914,Too many local variables (20/15),,0,
1037,r2/lib/pages/pages.py,2938,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1038,r2/lib/pages/pages.py,2935,W0231,__init__ method from base class 'CachedTemplate' is not called,,0,
1039,r2/lib/pages/pages.py,2935,W0613,Unused argument 'emails',,0,
1040,r2/lib/pages/pages.py,3008,W0621,Redefining name 'Trophy' from outer scope (line 29),,0,
1041,r2/lib/pages/pages.py,3008,W0404,Reimport 'Trophy' (imported line 29),,0,
1042,r2/lib/pages/pages.py,3032,R0914,Too many local variables (20/15),,0,
1043,r2/lib/pages/pages.py,3109,R0913,Too many arguments (6/5),,0,
1044,r2/lib/pages/pages.py,3153,C0324,Comma not followed by a space,,0,
1047,r2/lib/pages/pages.py,3175,R0913,Too many arguments (10/5),,0,
1048,r2/lib/pages/pages.py,3175,R0914,Too many local variables (24/15),,0,
1049,r2/lib/pages/pages.py,3188,W0621,Redefining name 'tup' from outer scope (line 134),,0,
1050,r2/lib/pages/pages.py,3175,W0102,Dangerous default value [] as argument,,0,
1051,r2/lib/pages/pages.py,3219,W0612,Unused variable 'target',,0,
1052,r2/lib/pages/pages.py,3327,W0613,Unused argument 'user',,0,
1053,r2/lib/pages/pages.py,3358,R0913,Too many arguments (6/5),,0,
1054,r2/lib/pages/pages.py,3384,R0913,Too many arguments (6/5),,0,
1055,r2/lib/pages/pages.py,3450,W0201,Attribute '_id' defined outside __init__,,0,
1056,r2/lib/pages/pages.py,3556,R0914,Too many local variables (19/15),,0,
1057,r2/lib/pages/pages.py,3608,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1058,r2/lib/pages/pages.py,3556,W0231,__init__ method from base class 'CachedTemplate' is not called,,0,
1059,r2/lib/pages/pages.py,3586,W0631,Using possibly undefined loop variable 'template',,,
1060,r2/lib/pages/pages.py,3631,C0322,Operator not preceded by a space,,0,
1063,r2/lib/pages/pages.py,3634,W0403,Relative import 'admin_pages',should be 'r2.lib.pages.admin_pages',0,
1064,r2/lib/pages/pages.py,3708,W0621,Redefining name 'menu' from outer scope (line 115),,0,
1065,r2/lib/pages/pages.py,3727,W0612,Unused variable 'default',,0,
1066,r2/lib/pages/pages.py,3759,W0201,Attribute 'regions' defined outside __init__,,0,
1067,r2/lib/pages/pages.py,3763,W0201,Attribute 'collections' defined outside __init__,,0,
1068,r2/lib/pages/pages.py,3760,W0201,Attribute 'metros' defined outside __init__,,0,
1069,r2/lib/pages/pages.py,3758,W0201,Attribute 'countries' defined outside __init__,,0,
1070,r2/lib/pages/pages.py,3770,R0902,Too many instance attributes (17/7),,0,
1071,r2/lib/pages/pages.py,3773,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1072,r2/lib/pages/pages.py,3771,W0231,__init__ method from base class 'PromoteLinkBase' is not called,,0,
1073,r2/lib/pages/pages.py,3775,R0914,Too many local variables (27/15),,0,
1074,r2/lib/pages/pages.py,3838,W0201,Attribute 'campaigns' defined outside __init__,,0,
1075,r2/lib/pages/pages.py,3841,W0201,Attribute 'min_bid' defined outside __init__,,0,
1076,r2/lib/pages/pages.py,3879,W0201,Attribute 'price_dict' defined outside __init__,,0,
1077,r2/lib/pages/pages.py,3777,W0201,Attribute 'author' defined outside __init__,,0,
1078,r2/lib/pages/pages.py,3869,W0201,Attribute 'inventory' defined outside __init__,,0,
1079,r2/lib/pages/pages.py,3833,W0201,Attribute 'default_end' defined outside __init__,,0,
1080,r2/lib/pages/pages.py,3836,W0201,Attribute 'listing' defined outside __init__,,0,
1081,r2/lib/pages/pages.py,3776,W0201,Attribute 'bids' defined outside __init__,,0,
1082,r2/lib/pages/pages.py,3843,W0201,Attribute 'priorities' defined outside __init__,,0,
1083,r2/lib/pages/pages.py,3835,W0201,Attribute 'link' defined outside __init__,,0,
1084,r2/lib/pages/pages.py,3839,W0201,Attribute 'promotion_log' defined outside __init__,,0,
1085,r2/lib/pages/pages.py,3854,W0201,Attribute 'subreddit_selector' defined outside __init__,,0,
1086,r2/lib/pages/pages.py,3878,W0201,Attribute 'infobar' defined outside __init__,,0,
1087,r2/lib/pages/pages.py,3832,W0201,Attribute 'default_start' defined outside __init__,,0,
1088,r2/lib/pages/pages.py,3882,R0902,Too many instance attributes (17/7),,0,
1089,r2/lib/pages/pages.py,3883,R0913,Too many arguments (7/5),,0,
1090,r2/lib/pages/pages.py,3963,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1091,r2/lib/pages/pages.py,3961,W0231,__init__ method from base class 'PromoteLinkBase' is not called,,0,
1092,r2/lib/pages/pages.py,3979,W0612,Unused variable 'pane',,0,
1093,r2/lib/pages/pages.py,4048,C0321,More than one statement on a single line,,0,
1094,r2/lib/pages/pages.py,4080,E1101,Module 'hashlib' has no 'sha1' member,,1,
1095,r2/lib/pages/pages.py,4101,R0913,Too many arguments (17/5),,0,
1096,r2/lib/pages/pages.py,4101,R0914,Too many local variables (19/15),,0,
1097,r2/lib/pages/pages.py,4192,R0902,Too many instance attributes (12/7),,0,
1098,r2/lib/pages/pages.py,4194,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1099,r2/lib/pages/pages.py,4193,W0231,__init__ method from base class 'PromoteLinkBase' is not called,,0,
1100,r2/lib/pages/pages.py,4211,R0914,Too many local variables (28/15),,0,
1101,r2/lib/pages/pages.py,4275,W0201,Attribute 'rows' defined outside __init__,,0,
1102,r2/lib/pages/pages.py,4235,W0201,Attribute 'header' defined outside __init__,,0,
1103,r2/lib/pages/pages.py,4280,W0201,Attribute 'subreddit_selector' defined outside __init__,,0,
1104,r2/lib/pages/pages.py,4288,R0902,Too many instance attributes (10/7),,0,
1105,r2/lib/pages/pages.py,4289,R0913,Too many arguments (7/5),,0,
1106,r2/lib/pages/pages.py,4305,W0233,__init__ method from a non direct base class 'Templated' is called,,0,
1107,r2/lib/pages/pages.py,4289,W0231,__init__ method from base class 'PromoteLinkBase' is not called,,0,
1108,r2/lib/pages/pages.py,4376,R0914,Too many local variables (18/15),,0,
1109,r2/lib/pages/pages.py,4389,W0612,Unused variable 'uniques',,0,
1110,r2/lib/pages/pages.py,4413,R0914,Too many local variables (16/15),,0,
1111,r2/lib/pages/pages.py,4428,W0201,Attribute 'clicks_by_link' defined outside __init__,,0,
1112,r2/lib/pages/pages.py,4429,W0201,Attribute 'impressions_by_link' defined outside __init__,,0,
1113,r2/lib/pages/pages.py,4460,W0231,__init__ method from base class 'Templated' is not called,,0,
1114,r2/lib/pages/pages.py,4463,W0613,Unused argument 'a',,0,
1115,r2/lib/pages/pages.py,4463,W0613,Unused argument 'kw',,0,
1116,r2/lib/pages/pages.py,4508,R0902,Too many instance attributes (8/7),,1,
1117,r2/lib/pages/pages.py,4509,R0913,Too many arguments (9/5),,1,
1118,r2/lib/pages/pages.py,4509,W0622,Redefining built-in 'id',,0,
1119,r2/lib/pages/pages.py,4509,W0102,Dangerous default value [] as argument,,0,
1120,r2/lib/pages/pages.py,4579,R0913,Too many arguments (6/5),,1,
1121,r2/lib/pages/pages.py,4636,R0913,Too many arguments (7/5),,1,
1122,r2/lib/pages/pages.py,4702,R0913,Too many arguments (6/5),,1,
1123,r2/lib/pages/pages.py,4770,R0913,Too many arguments (6/5),,1,
1126,r2/lib/pages/things.py,38,R0913,Too many arguments (12/5),,0,
1127,r2/lib/pages/things.py,38,R0914,Too many local variables (16/15),,0,
1128,r2/lib/pages/things.py,111,W0612,Unused variable 'now',,0,
1129,r2/lib/pages/things.py,183,W0613,Unused argument 'report',,0,
1130,r2/lib/pages/things.py,183,W0613,Unused argument 'delete',,0,
1131,r2/lib/pages/things.py,225,R0913,Too many arguments (6/5),,0,
1132,r2/lib/pages/admin_pages.py,43,W0621,Redefining name 'admin_menu' from outer scope (line 36),,0,
1133,r2/lib/pages/admin_pages.py,81,W0613,Unused argument 'link',,0,
1134,r2/lib/pages/admin_pages.py,113,C0321,More than one statement on a single line,,0,
1136,r2/lib/pages/wiki.py,31,R0902,Too many instance attributes (9/7),,0,
1137,r2/lib/pages/wiki.py,32,R0913,Too many arguments (8/5),,0,
1138,r2/lib/pages/wiki.py,73,R0913,Too many arguments (6/5),,0,
1139,r2/lib/pages/wiki.py,73,W0613,Unused argument 'context',,0,
1140,r2/lib/pages/wiki.py,99,R0913,Too many arguments (8/5),,0,
1143,r2/lib/pages/trafficpages.py,121,R0914,Too many local variables (18/15),,0,
1144,r2/lib/pages/trafficpages.py,129,W0201,Attribute 'tables' defined outside __init__,,0,
1145,r2/lib/pages/trafficpages.py,186,W0201,Attribute 'dow_means' defined outside __init__,,0,
1146,r2/lib/pages/trafficpages.py,172,W0201,Attribute 'dow_summary' defined outside __init__,,0,
1147,r2/lib/pages/trafficpages.py,298,W0622,Redefining built-in 'id',,0,
1148,r2/lib/pages/trafficpages.py,297,W0201,Attribute 'advert_summary' defined outside __init__,,0,
1149,r2/lib/pages/trafficpages.py,285,W0201,Attribute 'totals' defined outside __init__,,0,
1150,r2/lib/pages/trafficpages.py,527,R0902,Too many instance attributes (18/7),,0,
1151,r2/lib/pages/trafficpages.py,541,W0612,Unused variable 'editable',,0,
1152,r2/lib/pages/trafficpages.py,550,R0913,Too many arguments (14/5),,0,
1153,r2/lib/pages/trafficpages.py,550,R0914,Too many local variables (17/15),,0,
1154,r2/lib/pages/trafficpages.py,550,W0622,Redefining built-in 'id',,0,
1155,r2/lib/pages/trafficpages.py,588,R0914,Too many local variables (23/15),,0,
1156,r2/lib/pages/trafficpages.py,607,W0612,Unused variable 'date',,0,
1157,r2/lib/pages/trafficpages.py,717,W0612,Unused variable 'ctr',,0,
1158,r2/lib/pages/trafficpages.py,716,W0612,Unused variable 'datestr',,0,
1159,r2/lib/pages/trafficpages.py,716,W0612,Unused variable 'date',,0,
1160,r2/lib/pages/trafficpages.py,747,W0612,Unused variable 'datestr',,0,
1161,r2/lib/pages/trafficpages.py,721,W0201,Attribute 'total_ctr' defined outside __init__,,0,
1162,r2/lib/pages/trafficpages.py,715,W0201,Attribute 'total_impressions' defined outside __init__,,0,
1163,r2/lib/pages/trafficpages.py,715,W0201,Attribute 'total_clicks' defined outside __init__,,0,
1164,r2/lib/pages/trafficpages.py,713,W0201,Attribute 'history' defined outside __init__,,0,
1165,r2/lib/pages/trafficpages.py,728,W0201,Attribute 'is_preliminary' defined outside __init__,,0,
1166,r2/lib/pages/trafficpages.py,596,W0201,Attribute 'campaign_table' defined outside __init__,,0,
1167,r2/lib/pages/trafficpages.py,790,W0612,Unused variable 'url',,0,
1169,r2/lib/migrate/mr_domains.py,102,R0914,Too many local variables (18/15),,0,
1170,r2/lib/migrate/mr_domains.py,126,W0612,Unused variable 'sr_str',,0,
1171,r2/lib/migrate/mr_domains.py,117,W0612,Unused variable 'acc_str',,0,
1172,r2/lib/migrate/mr_domains.py,138,W0612,Unused variable 'd_str',,0,
1173,r2/lib/migrate/comment_sorts.py,60,E1101,Class 'CommentSortsCache' has no '_cf' member,,1,
1175,r2/lib/migrate/campaigns_to_things.py,27,R0914,Too many local variables (20/15),,0,
1176,r2/lib/migrate/campaigns_to_things.py,61,W0621,Redefining name 'c' from outer scope (line 25),,0,
1177,r2/lib/migrate/campaigns_to_things.py,77,W0702,No exception type(s) specified,,0,
1178,r2/lib/migrate/campaigns_to_things.py,72,W0612,Unused variable 'ed',,0,
1179,r2/lib/migrate/campaigns_to_things.py,72,W0612,Unused variable 'bid',,0,
1180,r2/lib/migrate/campaigns_to_things.py,72,W0612,Unused variable 'sr_name',,0,
1181,r2/lib/migrate/campaigns_to_things.py,72,W0612,Unused variable 'sd',,0,
1185,r2/lib/migrate/mr_permacache.py,134,W0621,Redefining name 'time' from outer scope (line 101),,0,
1186,r2/lib/migrate/mr_permacache.py,179,R0914,Too many local variables (16/15),,0,
1187,r2/lib/migrate/mr_permacache.py,196,W0621,Redefining name 'time' from outer scope (line 101),,0,
1188,r2/lib/migrate/mr_permacache.py,196,W0612,Unused variable 'sr_str',,0,
1189,r2/lib/migrate/mr_permacache.py,188,W0612,Unused variable 'acc_str',,0,
1190,r2/lib/migrate/mr_permacache.py,220,W0102,Dangerous default value [3] as argument,,0,
1192,r2/lib/migrate/migrate.py,30,W0621,Redefining name 'Subreddit' from outer scope (line 26),,0,
1193,r2/lib/migrate/migrate.py,34,C0324,Comma not followed by a space,,0,
1197,r2/lib/migrate/migrate.py,37,C0321,More than one statement on a single line,,0,
1198,r2/lib/migrate/migrate.py,42,W0621,Redefining name 'Subreddit' from outer scope (line 26),,0,
1199,r2/lib/migrate/migrate.py,42,W0621,Redefining name 'Account' from outer scope (line 26),,0,
1200,r2/lib/migrate/migrate.py,41,W0612,Unused variable 'sleep',,0,
1201,r2/lib/migrate/migrate.py,68,W0621,Redefining name 'Account' from outer scope (line 26),,0,
1202,r2/lib/migrate/migrate.py,69,W0621,Redefining name 'g' from outer scope (line 26),,0,
1203,r2/lib/migrate/migrate.py,77,E0602,Undefined variable 'Message',,1,
1204,r2/lib/migrate/migrate.py,77,E0602,Undefined variable 'Message',,1,
1205,r2/lib/migrate/migrate.py,78,E0602,Undefined variable 'desc',,1,
1206,r2/lib/migrate/migrate.py,80,E0602,Undefined variable 'fetch_things2',,1,
1207,r2/lib/migrate/migrate.py,81,C0324,Comma not followed by a space,,0,
1210,r2/lib/migrate/migrate.py,83,E1120,No value passed for parameter 'unread' in function call,,0,This is going to crash the program..
1211,r2/lib/migrate/migrate.py,87,E0602,Undefined variable 'Comment',,1,
1212,r2/lib/migrate/migrate.py,87,E0602,Undefined variable 'Comment',,1,
1213,r2/lib/migrate/migrate.py,88,E0602,Undefined variable 'desc',,1,
1214,r2/lib/migrate/migrate.py,89,E0602,Undefined variable 'Comment',,1,
1215,r2/lib/migrate/migrate.py,91,E0602,Undefined variable 'fetch_things2',,1,
1216,r2/lib/migrate/migrate.py,92,C0324,Comma not followed by a space,,0,
1219,r2/lib/migrate/migrate.py,93,E1120,No value passed for parameter 'unread' in function call,,0,This is going to crash the program..
1220,r2/lib/migrate/migrate.py,67,W0612,Unused variable 'cache',,0,
1221,r2/lib/migrate/migrate.py,104,W0621,Redefining name 'Account' from outer scope (line 26),,0,
1222,r2/lib/migrate/migrate.py,110,E0602,Undefined variable 'desc',,1,
1223,r2/lib/migrate/migrate.py,114,E0602,Undefined variable 'fetch_things2',,1,
1224,r2/lib/migrate/migrate.py,136,R0914,Too many local variables (21/15),,0,
1225,r2/lib/migrate/migrate.py,141,W0621,Redefining name 'Account' from outer scope (line 26),,0,
1226,r2/lib/migrate/migrate.py,141,W0621,Redefining name 'Link' from outer scope (line 26),,0,
1227,r2/lib/migrate/migrate.py,140,W0621,Redefining name 'g' from outer scope (line 26),,0,
1228,r2/lib/migrate/migrate.py,141,W0621,Redefining name 'Subreddit' from outer scope (line 26),,0,
1229,r2/lib/migrate/migrate.py,146,E0611,No name 'promoted_memo_key' in module 'r2.lib.promote',,0,
1230,r2/lib/migrate/migrate.py,209,W0621,Redefining name 'time' from outer scope (line 26),,0,
1231,r2/lib/migrate/migrate.py,190,E1101,Instance of 'FakeQuery' has no 'iden' member,,0,
1232,r2/lib/migrate/migrate.py,191,E1101,Instance of 'MergedCachedQuery' has no 'iden' member,,0,
1233,r2/lib/migrate/migrate.py,210,E1123,Passing unexpected keyword argument 'merge_batched' in function call,,0,
1234,r2/lib/migrate/migrate.py,216,E1101,Instance of 'Relations' has no 'iden' member,,0,
1235,r2/lib/migrate/migrate.py,217,E1101,Instance of 'Relations' has no 'iden' member,,0,
1236,r2/lib/migrate/migrate.py,227,R0914,Too many local variables (22/15),,0,
1237,r2/lib/migrate/migrate.py,228,W0621,Redefining name 'Account' from outer scope (line 26),,0,
1238,r2/lib/migrate/migrate.py,228,W0621,Redefining name 'Link' from outer scope (line 26),,0,
1239,r2/lib/migrate/migrate.py,229,E0611,No name 'CassandraVote' in module 'r2.models.vote',,0,
1240,r2/lib/migrate/migrate.py,229,E0611,No name 'CassandraLinkVote' in module 'r2.models.vote',,0,
1241,r2/lib/migrate/migrate.py,229,E0611,No name 'CassandraCommentVote' in module 'r2.models.vote',,0,
1242,r2/lib/migrate/migrate.py,239,E0602,Undefined variable 'desc',,1,
1243,r2/lib/migrate/migrate.py,229,W0612,Unused variable 'CassandraVote',,0,
1244,r2/lib/migrate/migrate.py,258,R0914,Too many local variables (16/15),,0,
1245,r2/lib/migrate/migrate.py,259,W0621,Redefining name 'Link' from outer scope (line 26),,0,
1246,r2/lib/migrate/migrate.py,268,C0324,Comma not followed by a space,,0,
1249,r2/lib/migrate/migrate.py,277,E1101,Class 'LinksByUrl' has no '_cf' member,,1,
1250,r2/lib/migrate/migrate.py,260,W0612,Unused variable 'tdb_cassandra',,0,
1251,r2/lib/migrate/migrate.py,284,W0621,Redefining name 'Link' from outer scope (line 26),,0,
1252,r2/lib/migrate/migrate.py,283,W0613,Unused argument 'after_id',,0,
1253,r2/lib/migrate/migrate.py,304,W0621,Redefining name 'json' from outer scope (line 26),,0,
1254,r2/lib/migrate/migrate.py,306,E1101,Class 'UserQueryCache' has no '_cf' member,,1,
1255,r2/lib/migrate/migrate.py,307,E1101,Class 'UserQueryCache' has no '_cf' member,,1,
1256,r2/lib/migrate/migrate.py,337,W0621,Redefining name 'c' from outer scope (line 26),,0,
1257,r2/lib/migrate/migrate.py,329,E0602,Undefined variable 'asc',,1,
1258,r2/lib/migrate/migrate.py,330,E0602,Undefined variable 'fetch_things2',,1,
1259,r2/lib/migrate/migrate.py,332,E0602,Undefined variable 'Thing',,1,
1260,r2/lib/migrate/migrate.py,334,E0602,Undefined variable 'Thing',,1,
1261,r2/lib/authorize/interaction.py,77,W0612,Unused variable 'cust_id',,0,
1262,r2/lib/authorize/interaction.py,111,R0913,Too many arguments (7/5),,0,
1263,r2/lib/authorize/interaction.py,130,E1101,Instance of 'dict' has no 'ERRORCARD' member,,0,
1264,r2/lib/authorize/interaction.py,192,C0321,More than one statement on a single line,,0,
1265,r2/lib/authorize/__init__.py,23,W0403,Relative import 'api',should be 'r2.lib.authorize.api',0,
1267,r2/lib/authorize/__init__.py,24,W0403,Relative import 'interaction',should be 'r2.lib.authorize.interaction',0,
1269,r2/lib/authorize/api.py,205,R0913,Too many arguments (6/5),,0,
1270,r2/lib/authorize/api.py,264,E1101,Instance of 'ParseResult' has no 'path' member,,,
1271,r2/lib/authorize/api.py,380,W0612,Unused variable 'u',,0,
1272,r2/lib/authorize/api.py,415,W0105,String statement has no effect,,0,Nearly ok.
1273,r2/lib/authorize/api.py,421,E1101,Instance of 'GetCustomerPaymentProfileRequest' has no 'customerPaymentProfileId' member,,,
1274,r2/lib/authorize/api.py,426,E1101,Instance of 'GetCustomerPaymentProfileRequest' has no 'customerPaymentProfileId' member,,,
1275,r2/lib/authorize/api.py,443,E1101,Instance of 'GetCustomerShippingAddressRequest' has no 'customerAddressId' member,,,
1276,r2/lib/authorize/api.py,448,E1101,Instance of 'GetCustomerShippingAddressRequest' has no 'customerAddressId' member,,,
1277,r2/lib/authorize/api.py,483,E1101,Instance of 'Address' has no 'customerAddressId' member,,,
1278,r2/lib/authorize/api.py,491,E1101,Instance of 'Address' has no 'customerPaymentProfileId' member,,,
1279,r2/lib/authorize/api.py,492,E1101,Instance of 'Address' has no 'customerPaymentProfileId' member,,,
1280,r2/lib/authorize/api.py,467,W0612,Unused variable 'fullname',,0,
1281,r2/lib/authorize/api.py,517,E1101,Instance of 'DeleteCustomerPaymentProfileRequest' has no 'customerPaymentProfileId' member,,,
1282,r2/lib/authorize/api.py,522,E1101,Instance of 'DeleteCustomerPaymentProfileRequest' has no 'customerPaymentProfileId' member,,,
1283,r2/lib/authorize/api.py,531,E1101,Instance of 'DeleteCustomerShippingAddressRequest' has no 'customerAddressId' member,,,
1284,r2/lib/authorize/api.py,536,E1101,Instance of 'DeleteCustomerShippingAddressRequest' has no 'customerAddressId' member,,,
1285,r2/lib/authorize/api.py,544,R0913,Too many arguments (6/5),,,
1286,r2/lib/authorize/api.py,546,W0233,__init__ method from a non direct base class 'CustomerRequest' is called,,0,
1287,r2/lib/authorize/api.py,544,W0231,__init__ method from base class 'CreateCustomerPaymentProfileRequest' is not called,,,
1288,r2/lib/authorize/api.py,553,E1101,Instance of 'UpdateCustomerPaymentProfileRequest' has no 'paymentProfile' member,,,
1289,r2/lib/authorize/api.py,608,W0621,Redefining name 'g' from outer scope (line 38),,0,
1290,r2/lib/authorize/api.py,608,W0404,Reimport 'g' (imported line 38),,0,
1291,r2/lib/authorize/api.py,608,W0612,Unused variable 'g',,0,
1292,r2/lib/traffic/emr_traffic.py,77,C0202,Class method should have 'cls' as first argument,,0,
1293,r2/lib/traffic/emr_traffic.py,165,R0913,Too many arguments (6/5),,0,
1294,r2/lib/traffic/__init__.py,23,W0403,Relative import 'traffic',should be 'r2.lib.traffic.traffic',0,
1296,r2/lib/traffic/traffic.py,92,W0612,Unused variable 'i',,1,
1297,r2/lib/traffic/traffic.py,169,R0914,Too many local variables (20/15),,0,
1298,r2/lib/traffic/traffic.py,218,E1101,Instance of 'ScopedSession' has no 'merge' member,,0,
1299,r2/lib/traffic/traffic.py,219,E1101,Instance of 'ScopedSession' has no 'commit' member,,1,
1300,r2/lib/traffic/traffic.py,368,W0612,Unused variable 'c',,1,
1301,r2/lib/db/userrel.py,89,R0902,Too many instance attributes (8/7),,0,
1302,r2/lib/db/userrel.py,92,R0913,Too many arguments (6/5),,0,
1303,r2/lib/db/userrel.py,147,W0232,Class has no __init__ method,,1,
1305,r2/lib/db/tdb_cassandra.py,1125,W0311,Bad indentation. Found 13 spaces,expected 12,0,
1306,r2/lib/db/tdb_cassandra.py,1126,W0311,Bad indentation. Found 17 spaces,expected 16,0,
1312,r2/lib/db/tdb_cassandra.py,123,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1313,r2/lib/db/tdb_cassandra.py,190,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1314,r2/lib/db/tdb_cassandra.py,209,E1101,Class 'Counter' has no '_cf' member,,1,Superclass 'ThingMeta' has '_cf'
1315,r2/lib/db/tdb_cassandra.py,214,E1101,Class 'Counter' has no '_cf' member,,1,
1316,r2/lib/db/tdb_cassandra.py,219,E1101,Class 'Counter' has no '_cf' member,,1,
1317,r2/lib/db/tdb_cassandra.py,223,R0902,Too many instance attributes (8/7),,0,
1318,r2/lib/db/tdb_cassandra.py,372,E1101,Class 'ThingBase' has no '_cf' member,,1,
1319,r2/lib/db/tdb_cassandra.py,381,E1101,Class 'ThingBase' has no '_cf' member,,1,
1320,r2/lib/db/tdb_cassandra.py,386,E1101,Class 'ThingBase' has no '_cf' member,,1,
1321,r2/lib/db/tdb_cassandra.py,468,E1101,Class 'ThingBase' has no '_write_consistency_level' member,,0,
1322,r2/lib/db/tdb_cassandra.py,470,E0213,"Method should have ""self"" as first argument",,0,Dead code again..
1323,r2/lib/db/tdb_cassandra.py,479,E1101,Class 'ThingBase' has no '_cf' member,,1,
1324,r2/lib/db/tdb_cassandra.py,480,E1101,Class 'ThingBase' has no '_cf' member,,1,
1325,r2/lib/db/tdb_cassandra.py,483,R0911,Too many return statements (8/6),,0,
1326,r2/lib/db/tdb_cassandra.py,505,R0911,Too many return statements (7/6),,0,
1327,r2/lib/db/tdb_cassandra.py,569,W0621,Redefining name 'write_consistency_level' from outer scope (line 61),,0,
1328,r2/lib/db/tdb_cassandra.py,830,W0622,Redefining built-in 'id',,0,
1329,r2/lib/db/tdb_cassandra.py,907,E1101,Class 'DenormalizedRelation' has no '_cf' member,,1,
1330,r2/lib/db/tdb_cassandra.py,909,E1101,Class 'DenormalizedRelation' has no '_views' member,,0,
1331,r2/lib/db/tdb_cassandra.py,921,E1101,Class 'DenormalizedRelation' has no '_cf' member,,1,
1332,r2/lib/db/tdb_cassandra.py,923,E1101,Class 'DenormalizedRelation' has no '_views' member,,0,
1333,r2/lib/db/tdb_cassandra.py,953,E1101,Class 'DenormalizedRelation' has no '_cf' member,,1,
1334,r2/lib/db/tdb_cassandra.py,972,R0902,Too many instance attributes (10/7),,0,
1335,r2/lib/db/tdb_cassandra.py,978,R0913,Too many arguments (9/5),,,
1336,r2/lib/db/tdb_cassandra.py,1042,R0914,Too many local variables (17/15),,,
1337,r2/lib/db/tdb_cassandra.py,1099,W0612,Unused variable 'is_single',,,
1338,r2/lib/db/tdb_cassandra.py,1133,W0621,Redefining name 'tup' from outer scope (line 44),,,
1339,r2/lib/db/tdb_cassandra.py,1138,W0621,Redefining name 'tup' from outer scope (line 44),,,
1340,r2/lib/db/tdb_cassandra.py,1175,R0913,Too many arguments (7/5),,,
1341,r2/lib/db/tdb_cassandra.py,1202,W0621,Redefining name 'write_consistency_level' from outer scope (line 61),,,
1342,r2/lib/db/tdb_cassandra.py,1210,W0101,Unreachable code,,0,
1343,r2/lib/db/tdb_cassandra.py,1275,W0612,Unused variable 'is_single',,,
1344,r2/lib/db/tdb_cassandra.py,1288,W0612,Unused variable 'is_single',,,
1345,r2/lib/db/tdb_cassandra.py,1323,E1101,Class 'View' has no '_cf' member,,,
1346,r2/lib/db/tdb_cassandra.py,1332,W0621,Redefining name 'write_consistency_level' from outer scope (line 61),,,
1347,r2/lib/db/tdb_cassandra.py,1348,E1101,Class 'View' has no '_cf' member,,,
1348,r2/lib/db/tdb_cassandra.py,1361,E1101,Class 'View' has no '_cf' member,,,
1349,r2/lib/db/tdb_cassandra.py,1429,E1120,No value passed for parameter 'seeds' in function call,,0,Dead code
1350,r2/lib/db/tdb_cassandra.py,1430,E1101,Instance of 'SystemManager' has no 'describe_keyspace' member,,,
1351,r2/lib/db/tdb_cassandra.py,1432,R0914,Too many local variables (19/15),,,
1352,r2/lib/db/tdb_cassandra.py,1444,W0622,Redefining built-in 'next',,,
1353,r2/lib/db/tdb_cassandra.py,1438,E1120,No value passed for parameter 'seeds' in function call,,0,Dead code
1354,r2/lib/db/thing.py,662,W0311,Bad indentation. Found 16 spaces,expected 12,,
1363,r2/lib/db/thing.py,38,C0321,More than one statement on a single line,,,
1364,r2/lib/db/thing.py,56,W0622,Redefining built-in 'id',,,
1365,r2/lib/db/thing.py,69,W0622,Redefining built-in 'type',,,
1366,r2/lib/db/thing.py,204,W0612,Unused variable 'old_val',,,
1367,r2/lib/db/thing.py,244,W0612,Unused variable 'old_value',,,
1368,r2/lib/db/thing.py,281,E1101,Class 'DataThing' has no '_type_id' member,,,
1369,r2/lib/db/thing.py,350,E1101,Class 'DataThing' has no '_type_prefix' member,,,
1370,r2/lib/db/thing.py,350,E1101,Class 'DataThing' has no '_type_id' member,,,
1371,r2/lib/db/thing.py,358,R0913,Too many arguments (7/5),,,
1372,r2/lib/db/thing.py,358,R0914,Too many local variables (19/15),,,
1373,r2/lib/db/thing.py,375,E1101,Class 'DataThing' has no '_type_id' member,,,
1374,r2/lib/db/thing.py,438,R0914,Too many local variables (18/15),,,
1375,r2/lib/db/thing.py,497,E0211,Method has no argument,,1,
1376,r2/lib/db/thing.py,500,E0211,Method has no argument,,1,
1377,r2/lib/db/thing.py,503,E0211,Method has no argument,,1,
1378,r2/lib/db/thing.py,506,E0211,Method has no argument,,1,
1379,r2/lib/db/thing.py,509,E0211,Method has no argument,,1,
1380,r2/lib/db/thing.py,117,W0201,Attribute '__dict__' defined outside __init__,,,
1381,r2/lib/db/thing.py,514,W0201,Attribute '_id' defined outside __init__,,,
1382,r2/lib/db/thing.py,518,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1383,r2/lib/db/thing.py,519,C0321,More than one statement on a single line,,,
1384,r2/lib/db/thing.py,529,W0602,Using global for 'thing_types' but no assignment is done,,1,The assignement is just after..
1385,r2/lib/db/thing.py,534,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1386,r2/lib/db/thing.py,537,R0902,Too many instance attributes (10/7),,,
1387,r2/lib/db/thing.py,549,R0913,Too many arguments (7/5),,,
1388,r2/lib/db/thing.py,550,W0622,Redefining built-in 'id',,,
1389,r2/lib/db/thing.py,559,C0321,More than one statement on a single line,,,
1390,r2/lib/db/thing.py,602,W0622,Redefining built-in 'id',,,
1391,r2/lib/db/thing.py,602,W0221,Arguments number differs from overridden method,,,
1392,r2/lib/db/thing.py,579,W0201,Attribute '_thing_id' defined outside __init__,,,
1393,r2/lib/db/thing.py,640,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1394,r2/lib/db/thing.py,641,C0321,More than one statement on a single line,,,
1395,r2/lib/db/thing.py,650,W0602,Using global for 'rel_types' but no assignment is done,,1,The assignement is just after..
1396,r2/lib/db/thing.py,655,C0203,"Metaclass method should have ""mcs"" as first argument",,0,
1397,r2/lib/db/thing.py,681,R0913,Too many arguments (7/5),,,
1398,r2/lib/db/thing.py,703,R0913,Too many arguments (6/5),,,
1399,r2/lib/db/thing.py,703,W0622,Redefining built-in 'id',,0,
1400,r2/lib/db/thing.py,718,C0321,More than one statement on a single line,,,
1401,r2/lib/db/thing.py,761,W0221,Arguments number differs from overridden method,,,
1402,r2/lib/db/thing.py,764,C0321,More than one statement on a single line,,,
1403,r2/lib/db/thing.py,765,C0321,More than one statement on a single line,,,
1404,r2/lib/db/thing.py,787,R0913,Too many arguments (7/5),,,
1405,r2/lib/db/thing.py,787,R0914,Too many local variables (23/15),,,
1406,r2/lib/db/thing.py,856,W0622,Redefining built-in 'id',,0,
1407,r2/lib/db/thing.py,856,W0221,Arguments number differs from overridden method,,0,
1408,r2/lib/db/thing.py,658,R0912,Too many branches (41/25),,0,
1409,r2/lib/db/thing.py,867,R0902,Too many instance attributes (11/7),,0,
1410,r2/lib/db/thing.py,883,W0621,Redefining name 'sorts' from outer scope (line 34),,0,
1411,r2/lib/db/thing.py,924,W0621,Redefining name 'sorts' from outer scope (line 34),,0,
1412,r2/lib/db/thing.py,962,E0211,Method has no argument,,1,
1413,r2/lib/db/thing.py,965,E0211,Method has no argument,,1,
1414,r2/lib/db/thing.py,979,E1101,Module 'hashlib' has no 'sha1' member,,1,
1415,r2/lib/db/thing.py,982,W0612,Unused variable 'used_cache',,0,
1416,r2/lib/db/thing.py,897,W0201,Attribute '_sort_param' defined outside __init__,,0,
1417,r2/lib/db/thing.py,1031,W0221,Arguments number differs from overridden method,,0,
1418,r2/lib/db/thing.py,1076,W0612,Unused variable 't2_items',,0,
1419,r2/lib/db/thing.py,1104,W0221,Arguments number differs from overridden method,,0,
1420,r2/lib/db/thing.py,1120,E1101,Instance of 'MultiCursor' has no '_execute' member,,1,
1421,r2/lib/db/thing.py,1126,E1101,Instance of 'MultiCursor' has no '_execute' member,,1,
1422,r2/lib/db/thing.py,1131,R0914,Too many local variables (18/15),,0,
1423,r2/lib/db/thing.py,1131,W0621,Redefining name 'sorts' from outer scope (line 34),,0,
1424,r2/lib/db/thing.py,1194,W0221,Arguments number differs from overridden method,,0,
1425,r2/lib/db/thing.py,1211,W0621,Redefining name 'sorts' from outer scope (line 34),,0,
1426,r2/lib/db/thing.py,1229,C0324,Comma not followed by a space,,0,
1429,r2/lib/db/thing.py,1248,W0701,Raising a string exception,,0,
1430,r2/lib/db/thing.py,1269,W0233,__init__ method from a non direct base class 'MultiRelationCls' is called,,0,
1431,r2/lib/db/thing.py,1287,R0913,Too many arguments (7/5),,0,
